const CATEGORIES = [
  {
    category_id: 1,
    category_name: "TRANG TRÍ NHÀ CỬA",
  },
  {
    category_id: 2,
    category_name: "NHÀ BẾP",
  },
  {
    category_id: 3,
    category_name: "NỘI THẤT",
  },
  {
    category_id: 4,
    category_name: "THỜI TRANG",
  },
];

const BLOGS = [
  {
    blog_id: 1,
    blog_title: "ECOKA chia sẻ hành trình chắp cánh thương hiệu Việt trên Amazon tại trường đại học FPT",
    blog_description: "Chủ tịch HĐQT Công ty cổ phần ECOKA, chị Quang Chân Chân, và Tổng Giám Đốc Công ty cổ phần, anh Hà AnhTrường, đã có một buổi chia sẻ đầy ý nghĩa tại trường đại học FPT về hành trình thành công của ECOKA trong việc đưa hàng Việt ra quốc tế trên sàn thương mại điện tử Amazon. Buổi chia sẻ, diễn ra vào ngày 23/6, đã gây được sự quan tâm và ngưỡng mộ từ các sinh viên.",
    blog_date: "28 Tháng 06, 2023",
    blog_author: "Trần My",
    blog_thumbnail: "https://file.hstatic.net/200000611203/article/chap_canh_thuong_hieu_viet__29__60cd4c08d9bc49f98cbc9a7d32cdd274.jpg",
    blog_section: [
      {
        section_id: 1,
        section_thumbnail: 'https://file.hstatic.net/200000611203/file/chap_canh_thuong_hieu_viet__79__d2d9e8ff2ae24f8e9774287d33f7a64d_grande.jpg',
        section_thumbnail_label: 'Chị Chân và anh Trường chia sẻ với sinh viên đại học FPT',
        section_content: 'Buổi chia sẻ đã truyền cảm hứng và khuyến khích sinh viên về khả năng của doanh nghiệp Việt trong việc vươn ra thị trường quốc tế. Chị Quang Chân Chân và anh Hà AnhTrường đã chia sẻ những kinh nghiệm quý báu về cách xây dựng và phát triển thương hiệu Việt trên môi trường cạnh tranh như Amazon. Điều này đã mở ra một cánh cửa mới cho các sinh viên, khuyến khích họ tiếp cận và tìm hiểu về cách một doanh nghiệp Việt có thể thành công trên sàn thương mại điện tử hàng đầu thế giới.'
      },
      {
        section_id: 2,
        section_thumbnail: 'https://file.hstatic.net/200000611203/file/chap_canh_thuong_hieu_viet__56__e52432f0b3754bee88d4ffc4df86b313_grande.jpg',
        section_thumbnail_label: 'Các bạn sinh viên FPT đặt câu hỏi cho hai diễn giả',
        section_content: 'Cuối buổi chia sẻ, ECOKA đã trao tặng một số phần quà đặc biệt, đó là những sản phẩm thủ công mỹ nghệ từ lục bình của ECOKA. Đây là một lời tri ân đặc biệt dành cho các sinh viên may mắn, đồng thời tạo cơ hội cho họ trải nghiệm và hiểu rõ hơn về nghệ thuật độc đáo và giá trị của những sản phẩm này.'
      }
    ]
  },
  {
    blog_id: 2,
    blog_title: "Phó Chủ tịch UBND tỉnh Hậu Giang thăm hỏi và động viên các doanh nghiệp",
    blog_description: "(NSMT) - Ngày 23/01, ông Trương Cảnh Tuyên - Phó Chủ tịch UBND tỉnh Hậu Giang và ông Nguyễn Vũ Trường - Chủ tịch UBND huyện Long Mỹ cùng lãnh đạo các sở, ban, ngành đã đến thăm và tặng quà cho một số doanh nghiệp trên địa bàn huyện Long Mỹ.",
    blog_date: "23/01/2024",
    blog_author: "Nhịp Sống Miền Tây",
    blog_thumbnail: "https://i.ex-cdn.com/mientay.giadinhonline.vn/files/content/2024/01/23/98976c98-4009-42a8-87ea-652ffbe7ab65-1636.jpg",
    blog_section: [
      {
        section_id: 1,
        section_thumbnail: 'https://i.ex-cdn.com/mientay.giadinhonline.vn/files/content/2024/01/23/98976c98-4009-42a8-87ea-652ffbe7ab65-1636.jpg',
        section_thumbnail_label: 'Các vị lãnh đạo tại Công ty Ecoka.',
        section_content: 'Tại các địa điểm, ông Trương Cảnh Tuyên và ông Nguyễn Vũ Trường đã giao lưu, chúc mừng và động viên các lãnh đạo, cán bộ, nhân viên của các doanh nghiệp, cũng như biểu dương những thành tích mà các doanh nghiệp đã đạt được trong năm 2023, đặc biệt là trong bối cảnh kinh tế nhiều biến động hiện nay do hậu quả đại dịch Covid để lại. Các đại biểu cũng đã lắng nghe và ghi nhận những ý kiến đóng góp, kiến nghị của các doanh nghiệp về các vấn đề liên quan đến môi trường kinh doanh, chính sách thuế, hỗ trợ tài chính, cung cấp nguồn nhân lực, cải thiện hạ tầng,...'
      },
      {
        section_id: 2,
        section_thumbnail: 'https://i.ex-cdn.com/mientay.giadinhonline.vn/files/content/2024/01/23/239d3ff9-95b1-4949-99af-413fc5c827e9-1636.jpg',
        section_thumbnail_label: 'Ông Trương Cảnh Tuyên tặng quà cho HTX Thuận Lợi.',
        section_content: 'Kết thúc chuyến thăm, các doanh nghiệp đã bày tỏ sự cảm kích và biết ơn đối với sự quan tâm và động viên của cấp tỉnh và cấp huyện, đồng thời cam kết sẽ nỗ lực hơn nữa trong công tác sản xuất kinh doanh, đảm bảo an toàn lao động, bảo vệ môi trường, thực hiện tốt các nghĩa vụ đối với nhà nước và xã hội, góp phần vào sự phát triển kinh tế - xã hội của huyện Long Mỹ và tỉnh Hậu Giang.'
      }
    ]
  },
  {
    blog_id: 3,
    blog_title: "Khởi nghiệp từ cây lục bình, chàng trai kiếm doanh thu hơn 2 tỉ đồng/tháng",
    blog_description: "Nhận thấy những vất vả của người dân làng nghề thủ công mỹ nghệ truyền thống, anh Hà Anh Trường (35 tuổi), ngụ tại P.9, TP.Vũng Tàu (tỉnh Bà Rịa - Vũng Tàu) đã đem sản phẩm làm từ cây lục bình đi xuất ngoại với doanh thu hơn 2 tỉ đồng/tháng.",
    blog_date: "19/10/2023",
    blog_author: "Báo Thanh Niên",
    blog_thumbnail: "https://images2.thanhnien.vn/thumb_w/640/528068263637045248/2023/10/18/base64-169763416686080802620.jpeg",
    blog_section: [
      {
        section_id: 1,
        section_thumbnail: 'https://images2.thanhnien.vn/thumb_w/640/528068263637045248/2023/10/18/base64-169763416686080802620.jpeg',
        section_thumbnail_label: 'Hà Anh Trường khởi nghiệp với cây lục bình',
        section_content: 'Năm 2018, trong quá trình tìm kiếm mặt hàng để khởi nghiệp mô hình kinh doanh thương mại điện tử, anh Hà Anh Trường đã chú ý đến các sản phẩm thủ công mỹ nghệ từ cây lục bình của làng nghề truyền thống.'
      },
      {
        section_id: 2,
        section_thumbnail: 'https://images2.thanhnien.vn/thumb_w/640/528068263637045248/2023/10/18/base64-1697634325867126376752.jpeg',
        section_thumbnail_label: 'Tạo nguồn thu nhập ổn định cho người dân làng nghề',
        section_content: '“Đa phần sản phẩm sẽ được thương lái thu mua rồi bán sang Trung Quốc theo kiểu gối đầu, làm mùa này nhưng đến đợt sau mới trả tiền. Tuy nhiên, khi thị trường không khả quan, thương lái sẽ bỏ hàng làm ảnh hưởng đến sinh kế của người dân. Đây cũng là lý do khiến nhiều người phải chuyển nghề”, anh Trường kể lại. \nVới mong muốn thay đổi đời sống của người dân, anh Trường cùng các cộng sự đã tiếp cận những người thợ lành nghề, thu mua và hướng dẫn họ cải tiến sản phẩm để làm sao xuất khẩu sang thị trường châu Âu. “Các sản phẩm từ lục bình rất thân thiện với môi trường, có thể phân hủy sinh học làm phân bón, giảm phát thải tiêu dùng hàng ngày. Do đó, được thị trường tại châu Âu ưa chuộng”, anh nói.'
      },
      {
        section_id: 3,
        section_thumbnail: 'https://images2.thanhnien.vn/528068263637045248/2023/10/18/z47955313726042da29c0da7f087866adbd86aac0c367d-16976339415291235375594.jpg',
        section_thumbnail_label: 'Anh Trường trong lần giới thiệu sản phẩm tại sự kiện Diễn đàn và Xuất khẩu TP.HCM 2023',
        section_content: 'Năm 2022, anh Trường thành lập công ty sản xuất và thương mại các sản phẩm thủ công mỹ nghệ từ lục bình, như: trang trí nhà cửa, đồ dùng phụ kiện bàn ăn, những sản phẩm thời trang nón, túi xách… với thị trường chủ lực ở Mỹ, Canada, Pháp đạt doanh thu hơn 2 tỉ đồng/tháng.'
      }
    ]
  },
];

const HOME_PRODUCTS = [
  {
    product_id: "ECOKAPRODUCT",
    product_name: "Giá Giày",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-v2.devilop.me/home/gia-giay/gia-giay_1.jpg',
    product_thumbnail_two: 'https://ecoka-v2.devilop.me/home/gia-giay/gia-giay_2.jpg',
    product_thumbnail_three: '',
    product_thumbnail_four: '',
    product_thumbnail_five: '',
    product_thumbnail_six: '',
    product_price: '0',
    category_id: 1
  },
  {
    product_id: "ECOKAPRODUCT",
    product_name: "Storage",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-v2.devilop.me/home/storage-01/storage-01_1.jpg',
    product_thumbnail_two: 'https://ecoka-v2.devilop.me/home/storage-01/storage-01_2.jpg',
    product_thumbnail_three: 'https://ecoka-v2.devilop.me/home/storage-01/storage-01_3.jpg',
    product_thumbnail_four: 'https://ecoka-v2.devilop.me/home/storage-01/storage-01_4.jpg',
    product_thumbnail_five: 'https://ecoka-v2.devilop.me/home/storage-01/storage-01_5.jpg',
    product_thumbnail_six: '',
    product_price: '0',
    category_id: 1
  },
  {
    product_id: "ECOKAPRODUCT",
    product_name: "Storage",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-v2.devilop.me/home/storage-02/storage-02_1.jpg',
    product_thumbnail_two: 'https://ecoka-v2.devilop.me/home/storage-02/storage-02_2.jpg',
    product_thumbnail_three: 'https://ecoka-v2.devilop.me/home/storage-02/storage-02_3.jpg',
    product_thumbnail_four: 'https://ecoka-v2.devilop.me/home/storage-02/storage-02_4.jpg',
    product_thumbnail_five: 'https://ecoka-v2.devilop.me/home/storage-02/storage-02_5.jpg',
    product_thumbnail_six: '',
    product_price: '0',
    category_id: 1
  },
  {
    product_id: "ECOKAPRODUCT",
    product_name: "Thảm Cỏ Biển 3ft",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-home.devilop.me/home/03/03_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-home.devilop.me/home/03/03_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-home.devilop.me/home/03/03_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-home.devilop.me/home/03/03_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-home.devilop.me/home/03/03_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-home.devilop.me/home/03/03_6.jpg',
    product_price: '0',
    category_id: 1
  },
  // ======================================
  {
    product_id: "ECOKAPRODUCT",
    product_name: "Giỏ Tre",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-kitchen.devilop.me/kitchen/09/09_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-kitchen.devilop.me/kitchen/09/09_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-kitchen.devilop.me/kitchen/09/09_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-kitchen.devilop.me/kitchen/09/09_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-kitchen.devilop.me/kitchen/09/09_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-kitchen.devilop.me/kitchen/09/09_6.jpg',
    product_price: '0',
    category_id: 2
  },
  {
    product_id: "ECOKAPRODUCT",
    product_name: "Bộ Lục Bình Trữ Nước 3-SF",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-kitchen.devilop.me/kitchen/17/17_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-kitchen.devilop.me/kitchen/17/17_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-kitchen.devilop.me/kitchen/17/17_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-kitchen.devilop.me/kitchen/17/17_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-kitchen.devilop.me/kitchen/17/17_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-kitchen.devilop.me/kitchen/17/17_6.jpg',
    product_price: '0',
    category_id: 2
  },
  {
    product_id: "ECOKAPRODUCT",
    product_name: "Giỏ Đựng Lục Bình Có Lỗ 3",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-kitchen.devilop.me/kitchen/15/15_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-kitchen.devilop.me/kitchen/15/15_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-kitchen.devilop.me/kitchen/15/15_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-kitchen.devilop.me/kitchen/15/15_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-kitchen.devilop.me/kitchen/15/15_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-kitchen.devilop.me/kitchen/15/15_6.jpg',
    product_price: '0',
    category_id: 2
  },
  {
    product_id: "ECOKAPRODUCT",
    product_name: "Lót Ly Macrame",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-kitchen.devilop.me/kitchen/11/11_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-kitchen.devilop.me/kitchen/11/11_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-kitchen.devilop.me/kitchen/11/11_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-kitchen.devilop.me/kitchen/11/11_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-kitchen.devilop.me/kitchen/11/11_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-kitchen.devilop.me/kitchen/11/11_6.jpg',
    product_price: '0',
    category_id: 2
  },
  // ======================================
  {
    product_id: "ECOKAPRODUCT",
    product_name: "Home Storage",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-v2.devilop.me/furniture/home-storage/home-storage_1.jpg',
    product_thumbnail_two: 'https://ecoka-v2.devilop.me/furniture/home-storage/home-storage_2.jpg',
    product_thumbnail_three: 'https://ecoka-v2.devilop.me/furniture/home-storage/home-storage_3.jpg',
    product_thumbnail_four: '',
    product_thumbnail_five: '',
    product_thumbnail_six: '',
    product_price: '0',
    category_id: 3
  },
  {
    product_id: "ECOKAPRODUCT",
    product_name: "Đôn",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-v2.devilop.me/furniture/don/don_1.jpg',
    product_thumbnail_two: 'https://ecoka-v2.devilop.me/furniture/don/don_2.jpg',
    product_thumbnail_three: '',
    product_thumbnail_four: '',
    product_thumbnail_five: '',
    product_thumbnail_six: '',
    product_price: '0',
    category_id: 3
  },
  {
    product_id: "ECOKAPRODUCT",
    product_name: "Chair",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-v2.devilop.me/furniture/chair/chair.jpg',
    product_thumbnail_two: '',
    product_thumbnail_three: '',
    product_thumbnail_four: '',
    product_thumbnail_five: '',
    product_thumbnail_six: '',
    product_price: '0',
    category_id: 3
  },
  {
    product_id: "ECOKAPRODUCT",
    product_name: "Coffee Table",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-v2.devilop.me/furniture/coffee-table/coffee-table.jpg',
    product_thumbnail_two: '',
    product_thumbnail_three: '',
    product_thumbnail_four: '',
    product_thumbnail_five: '',
    product_thumbnail_six: '',
    product_price: '0',
    category_id: 3
  },
  // ======================================
  {
    product_id: "ECOKAPRODUCT",
    product_name: "Túi 3 Tinh - Vàng Hồng Đỏ",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-fashion.devilop.me/fashion/19/19_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-fashion.devilop.me/fashion/19/19_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-fashion.devilop.me/fashion/19/19_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-fashion.devilop.me/fashion/19/19_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-fashion.devilop.me/fashion/19/19_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-fashion.devilop.me/fashion/19/19_6.jpg',
    product_price: '0',
    category_id: 4
  },
  {
    product_id: "ECOKAPRODUCT",
    product_name: "Túi 3 Màu - Vàng Nâu",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-fashion.devilop.me/fashion/20/20_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-fashion.devilop.me/fashion/20/20_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-fashion.devilop.me/fashion/20/20_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-fashion.devilop.me/fashion/20/20_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-fashion.devilop.me/fashion/20/20_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-fashion.devilop.me/fashion/20/20_6.jpg',
    product_price: '0',
    category_id: 4
  },
  {
    product_id: "ECOKAPRODUCT",
    product_name: "Túi 3 Màu - Màu Trắng Nâu",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-fashion.devilop.me/fashion/21/21_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-fashion.devilop.me/fashion/21/21_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-fashion.devilop.me/fashion/21/21_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-fashion.devilop.me/fashion/21/21_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-fashion.devilop.me/fashion/21/21_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-fashion.devilop.me/fashion/21/21_6.jpg',
    product_price: '0',
    category_id: 4
  },
  {
    product_id: "ECOKAPRODUCT",
    product_name: "Túi Cói Kem",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-fashion.devilop.me/fashion/22/22_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-fashion.devilop.me/fashion/22/22_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-fashion.devilop.me/fashion/22/22_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-fashion.devilop.me/fashion/22/22_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-fashion.devilop.me/fashion/22/22_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-fashion.devilop.me/fashion/22/22_6.jpg',
    product_price: '0',
    category_id: 4
  },
];

const PRODUCTS = [
  {
    product_id: "ECOKAPRODUCT",
    product_name: "Nhẫn Lục Bình",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-home.devilop.me/home/01/01_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-home.devilop.me/home/01/01_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-home.devilop.me/home/01/01_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-home.devilop.me/home/01/01_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-home.devilop.me/home/01/01_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-home.devilop.me/home/01/01_6.jpg',
    product_price: '0',
    category_id: 2
  },
  {
    product_id: "ECOKAPRODUCT",
    product_name: "Thảm Cỏ Biển Hoa 4ft",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-home.devilop.me/home/02/02_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-home.devilop.me/home/02/02_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-home.devilop.me/home/02/02_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-home.devilop.me/home/02/02_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-home.devilop.me/home/02/02_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-home.devilop.me/home/02/02_6.jpg',
    product_price: '0',
    category_id: 1
  },
  {
    product_id: "ECOKAPRODUCT",
    product_name: "Thảm Cỏ Biển 3ft",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-home.devilop.me/home/03/03_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-home.devilop.me/home/03/03_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-home.devilop.me/home/03/03_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-home.devilop.me/home/03/03_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-home.devilop.me/home/03/03_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-home.devilop.me/home/03/03_6.jpg',
    product_price: '0',
    category_id: 1
  },
  {
    product_id: "ECOKAPRODUCT",
    product_name: "Rèm Macrame-Màu Be",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-home.devilop.me/home/04/04_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-home.devilop.me/home/04/04_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-home.devilop.me/home/04/04_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-home.devilop.me/home/04/04_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-home.devilop.me/home/04/04_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-home.devilop.me/home/04/04_6.jpg',
    product_price: '0',
    category_id: 1
  },
  {
    product_id: "ECOKAPRODUCT",
    product_name: "Rèm Macrame-Vàng",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-home.devilop.me/home/05/05_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-home.devilop.me/home/05/05_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-home.devilop.me/home/05/05_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-home.devilop.me/home/05/05_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-home.devilop.me/home/05/05_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-home.devilop.me/home/05/05_6.jpg',
    product_price: '0',
    category_id: 1
  },
  {
    product_id: "ECOKAPRODUCT",
    product_name: "Rèm Macrame-Xám",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-home.devilop.me/home/06/06_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-home.devilop.me/home/06/06_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-home.devilop.me/home/06/06_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-home.devilop.me/home/06/06_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-home.devilop.me/home/06/06_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-home.devilop.me/home/06/06_6.jpg',
    product_price: '0',
    category_id: 1
  },
  {
    product_id: "ECOKAPRODUCT",
    product_name: "Rèm Macrarme-Nâu Hồng",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-home.devilop.me/home/07/07_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-home.devilop.me/home/07/07_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-home.devilop.me/home/07/07_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-home.devilop.me/home/07/07_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-home.devilop.me/home/07/07_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-home.devilop.me/home/07/07_6.jpg',
    product_price: '0',
    category_id: 1
  },
  {
    product_id: "ECOKAPRODUCT",
    product_name: "Rèm Lưới",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-home.devilop.me/home/08/08_1.png',
    product_thumbnail_two: 'https://ecoka-product-home.devilop.me/home/08/08_2.png',
    product_thumbnail_three: 'https://ecoka-product-home.devilop.me/home/08/08_3.png',
    product_thumbnail_four: 'https://ecoka-product-home.devilop.me/home/08/08_4.png',
    product_thumbnail_five: 'https://ecoka-product-home.devilop.me/home/08/08_5.png',
    product_thumbnail_six: 'https://ecoka-product-home.devilop.me/home/08/08_6.png',
    product_price: '0',
    category_id: 1
  },
  {
    product_id: "ECOKAPRODUCT",
    product_name: "Giỏ Tre",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-kitchen.devilop.me/kitchen/09/09_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-kitchen.devilop.me/kitchen/09/09_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-kitchen.devilop.me/kitchen/09/09_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-kitchen.devilop.me/kitchen/09/09_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-kitchen.devilop.me/kitchen/09/09_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-kitchen.devilop.me/kitchen/09/09_6.jpg',
    product_price: '0',
    category_id: 2
  },
  {
    product_id: "ECOKAPRODUCT",
    product_name: "Lót Ly Lục Bình",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-kitchen.devilop.me/kitchen/10/10_1.JPG',
    product_thumbnail_two: 'https://ecoka-product-kitchen.devilop.me/kitchen/10/10_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-kitchen.devilop.me/kitchen/10/10_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-kitchen.devilop.me/kitchen/10/10_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-kitchen.devilop.me/kitchen/10/10_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-kitchen.devilop.me/kitchen/10/10_6.jpg',
    product_price: '0',
    category_id: 2
  },
  {
    product_id: "ECOKAPRODUCT",
    product_name: "Lót Ly Macrame",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-kitchen.devilop.me/kitchen/11/11_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-kitchen.devilop.me/kitchen/11/11_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-kitchen.devilop.me/kitchen/11/11_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-kitchen.devilop.me/kitchen/11/11_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-kitchen.devilop.me/kitchen/11/11_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-kitchen.devilop.me/kitchen/11/11_6.jpg',
    product_price: '0',
    category_id: 2
  },
  {
    product_id: "ECOKAPRODUCT",
    product_name: "Giỏ Đựng Macrame 30cm-Beige",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-kitchen.devilop.me/kitchen/12/12_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-kitchen.devilop.me/kitchen/12/12_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-kitchen.devilop.me/kitchen/12/12_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-kitchen.devilop.me/kitchen/12/12_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-kitchen.devilop.me/kitchen/12/12_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-kitchen.devilop.me/kitchen/12/12_6.jpg',
    product_price: '0',
    category_id: 2
  },
  {
    product_id: "ECOKAPRODUCT",
    product_name: "Giỏ Đựng Macrame 30cm-Socola",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-kitchen.devilop.me/kitchen/13/13_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-kitchen.devilop.me/kitchen/13/13_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-kitchen.devilop.me/kitchen/13/13_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-kitchen.devilop.me/kitchen/13/13_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-kitchen.devilop.me/kitchen/13/13_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-kitchen.devilop.me/kitchen/13/13_6.jpg',
    product_price: '0',
    category_id: 2
  },
  {
    product_id: "ECOKAPRODUCT",
    product_name: "Giỏ Đựng Cỏ Biển Vuông 30cm",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-kitchen.devilop.me/kitchen/14/14_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-kitchen.devilop.me/kitchen/14/14_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-kitchen.devilop.me/kitchen/14/14_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-kitchen.devilop.me/kitchen/14/14_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-kitchen.devilop.me/kitchen/14/14_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-kitchen.devilop.me/kitchen/14/14_6.jpg',
    product_price: '0',
    category_id: 2
  },
  {
    product_id: "ECOKAPRODUCT",
    product_name: "Giỏ Đựng Lục Bình Có Lỗ 3",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-kitchen.devilop.me/kitchen/15/15_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-kitchen.devilop.me/kitchen/15/15_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-kitchen.devilop.me/kitchen/15/15_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-kitchen.devilop.me/kitchen/15/15_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-kitchen.devilop.me/kitchen/15/15_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-kitchen.devilop.me/kitchen/15/15_6.jpg',
    product_price: '0',
    category_id: 2
  },
  {
    product_id: "ECOKAPRODUCT",
    product_name: "Giỏ Đựng Lục Bình Xca Set 3",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-kitchen.devilop.me/kitchen/16/16_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-kitchen.devilop.me/kitchen/16/16_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-kitchen.devilop.me/kitchen/16/16_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-kitchen.devilop.me/kitchen/16/16_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-kitchen.devilop.me/kitchen/16/16_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-kitchen.devilop.me/kitchen/16/16_6.jpg',
    product_price: '0',
    category_id: 2
  },
  {
    product_id: "ECOKAPRODUCT",
    product_name: "Bộ Lục Bình Trữ Nước 3-SF",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-kitchen.devilop.me/kitchen/17/17_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-kitchen.devilop.me/kitchen/17/17_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-kitchen.devilop.me/kitchen/17/17_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-kitchen.devilop.me/kitchen/17/17_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-kitchen.devilop.me/kitchen/17/17_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-kitchen.devilop.me/kitchen/17/17_6.jpg',
    product_price: '0',
    category_id: 2
  },
  {
    product_id: "ECOKAPRODUCT",
    product_name: "Bình Lục Bình Vuông 30cm",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-kitchen.devilop.me/kitchen/18/18_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-kitchen.devilop.me/kitchen/18/18_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-kitchen.devilop.me/kitchen/18/18_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-kitchen.devilop.me/kitchen/18/18_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-kitchen.devilop.me/kitchen/18/18_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-kitchen.devilop.me/kitchen/18/18_6.jpg',
    product_price: '0',
    category_id: 2
  },
  {
    product_id: "ECOKAPRODUCT",
    product_name: "Túi 3 Tinh - Vàng Hồng Đỏ",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-fashion.devilop.me/fashion/19/19_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-fashion.devilop.me/fashion/19/19_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-fashion.devilop.me/fashion/19/19_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-fashion.devilop.me/fashion/19/19_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-fashion.devilop.me/fashion/19/19_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-fashion.devilop.me/fashion/19/19_6.jpg',
    product_price: '0',
    category_id: 4
  },
  {
    product_id: "ECOKAPRODUCT",
    product_name: "Túi 3 Màu - Vàng Nâu",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-fashion.devilop.me/fashion/20/20_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-fashion.devilop.me/fashion/20/20_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-fashion.devilop.me/fashion/20/20_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-fashion.devilop.me/fashion/20/20_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-fashion.devilop.me/fashion/20/20_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-fashion.devilop.me/fashion/20/20_6.jpg',
    product_price: '0',
    category_id: 4
  },
  {
    product_id: "ECOKAPRODUCT",
    product_name: "Túi 3 Màu - Màu Trắng Nâu",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-fashion.devilop.me/fashion/21/21_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-fashion.devilop.me/fashion/21/21_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-fashion.devilop.me/fashion/21/21_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-fashion.devilop.me/fashion/21/21_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-fashion.devilop.me/fashion/21/21_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-fashion.devilop.me/fashion/21/21_6.jpg',
    product_price: '0',
    category_id: 4
  },
  {
    product_id: "ECOKAPRODUCT",
    product_name: "Túi Cói Kem",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-fashion.devilop.me/fashion/22/22_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-fashion.devilop.me/fashion/22/22_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-fashion.devilop.me/fashion/22/22_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-fashion.devilop.me/fashion/22/22_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-fashion.devilop.me/fashion/22/22_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-fashion.devilop.me/fashion/22/22_6.jpg',
    product_price: '0',
    category_id: 4
  },
  {
    product_id: "ECOKAPRODUCT",
    product_name: "Túi Cói MixColor",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-fashion.devilop.me/fashion/23/23_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-fashion.devilop.me/fashion/23/23_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-fashion.devilop.me/fashion/23/23_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-fashion.devilop.me/fashion/23/23_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-fashion.devilop.me/fashion/23/23_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-fashion.devilop.me/fashion/23/23_6.jpg',
    product_price: '0',
    category_id: 4
  },
  {
    product_id: "ECOKAPRODUCT",
    product_name: "Túc Lục Bình",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-fashion.devilop.me/fashion/24/24_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-fashion.devilop.me/fashion/24/24_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-fashion.devilop.me/fashion/24/24_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-fashion.devilop.me/fashion/24/24_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-fashion.devilop.me/fashion/24/24_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-fashion.devilop.me/fashion/24/24_6.jpg',
    product_price: '0',
    category_id: 4
  },
  {
    product_id: "ECOKAPRODUCT",
    product_name: "Túi Lục Bình Chim Công",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-fashion.devilop.me/fashion/25/25_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-fashion.devilop.me/fashion/25/25_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-fashion.devilop.me/fashion/25/25_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-fashion.devilop.me/fashion/25/25_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-fashion.devilop.me/fashion/25/25_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-fashion.devilop.me/fashion/25/25_6.jpg',
    product_price: '0',
    category_id: 4
  },
  {
    product_id: "ECOKAPRODUCT",
    product_name: "Túi Lục Bình Hoa Độc",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-fashion.devilop.me/fashion/26/26_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-fashion.devilop.me/fashion/26/26_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-fashion.devilop.me/fashion/26/26_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-fashion.devilop.me/fashion/26/26_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-fashion.devilop.me/fashion/26/26_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-fashion.devilop.me/fashion/26/26_6.jpg',
    product_price: '0',
    category_id: 4
  },
  {
    product_id: "ECOKAPRODUCT",
    product_name: "Túi Lục Bình Hoa Miếng",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-fashion.devilop.me/fashion/27/27_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-fashion.devilop.me/fashion/27/27_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-fashion.devilop.me/fashion/27/27_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-fashion.devilop.me/fashion/27/27_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-fashion.devilop.me/fashion/27/27_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-fashion.devilop.me/fashion/27/27_6.jpg',
    product_price: '0',
    category_id: 4
  },
  {
    product_id: "ECOKAPRODUCT",
    product_name: "Túi Lục Bình Quay Đá 26",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-fashion.devilop.me/fashion/28/28_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-fashion.devilop.me/fashion/28/28_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-fashion.devilop.me/fashion/28/28_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-fashion.devilop.me/fashion/28/28_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-fashion.devilop.me/fashion/28/28_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-fashion.devilop.me/fashion/28/28_6.jpg',
    product_price: '0',
    category_id: 4
  },
  {
    product_id: "ECOKAPRODUCT",
    product_name: "Túi Lục Bình Quay Đà",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-fashion.devilop.me/fashion/29/29_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-fashion.devilop.me/fashion/29/29_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-fashion.devilop.me/fashion/29/29_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-fashion.devilop.me/fashion/29/29_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-fashion.devilop.me/fashion/29/29_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-fashion.devilop.me/fashion/29/29_6.jpg',
    product_price: '0',
    category_id: 4
  },
  {
    product_id: "ECOKAPRODUCT",
    product_name: "Túi Lục Bình Quay Da Macrame",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-fashion.devilop.me/fashion/30/30_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-fashion.devilop.me/fashion/30/30_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-fashion.devilop.me/fashion/30/30_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-fashion.devilop.me/fashion/30/30_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-fashion.devilop.me/fashion/30/30_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-fashion.devilop.me/fashion/30/30_6.jpg',
    product_price: '0',
    category_id: 4
  },
  {
    product_id: "ECOKAPRODUCT",
    product_name: "Túi Macrame Điện Thoại - Hồng",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-fashion.devilop.me/fashion/31/31_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-fashion.devilop.me/fashion/31/31_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-fashion.devilop.me/fashion/31/31_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-fashion.devilop.me/fashion/31/31_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-fashion.devilop.me/fashion/31/31_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-fashion.devilop.me/fashion/31/31_6.jpg',
    product_price: '0',
    category_id: 4
  },
  {
    product_id: "ECOKAPRODUCT",
    product_name: "Túi Macrame Điện Thoại - Kem",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-fashion.devilop.me/fashion/32/32_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-fashion.devilop.me/fashion/32/32_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-fashion.devilop.me/fashion/32/32_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-fashion.devilop.me/fashion/32/32_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-fashion.devilop.me/fashion/32/32_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-fashion.devilop.me/fashion/32/32_6.jpg',
    product_price: '0',
    category_id: 4
  },
  {
    product_id: "ECOKAPRODUCT",
    product_name: "Laptop 32 Túi Macrame",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-fashion.devilop.me/fashion/33/33_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-fashion.devilop.me/fashion/33/33_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-fashion.devilop.me/fashion/33/33_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-fashion.devilop.me/fashion/33/33_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-fashion.devilop.me/fashion/33/33_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-fashion.devilop.me/fashion/33/33_6.jpg',
    product_price: '0',
    category_id: 4
  },
  {
    product_id: "ECOKAPRODUCT",
    product_name: "Túi Macrame Ngang - Kem",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/34/34_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/34/34_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/34/34_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/34/34_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/34/34_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/34/34_6.jpg',
    product_price: '0',
    category_id: 4
  },
  {
    product_id: "ECOKAPRODUCT",
    product_name: "Túi Trống - Kem Nâu",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/35/35_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/35/35_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/35/35_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/35/35_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/35/35_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/35/35_6.jpg',
    product_price: '0',
    category_id: 4
  },
  {
    product_id: "ECOKAPRODUCT",
    product_name: "Túi Trống - Kem Vàng",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/36/36_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/36/36_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/36/36_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/36/36_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/36/36_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/36/36_6.jpg',
    product_price: '0',
    category_id: 4
  },
  {
    product_id: "ECOKAPRODUCT",
    product_name: "Mũ Đi Biển Hoa Lục Bình Cho Nữ Sang Trọng",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/37/37_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/37/37_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/37/37_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/37/37_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/37/37_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/37/37_6.jpg',
    product_price: '0',
    category_id: 4
  },
  {
    product_id: "ECOKAPRODUCT",
    product_name: "Mũ Đi Biển Lục Bình Dây Đơn Cho Nữ",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/38/38_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/38/38_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/38/38_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/38/38_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/38/38_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/38/38_6.jpg',
    product_price: '0',
    category_id: 4
  },
  // ======================================
  {
    product_id: "ECOKAPRODUCT",
    product_name: "Giá Giày",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-v2.devilop.me/home/gia-giay/gia-giay_1.jpg',
    product_thumbnail_two: 'https://ecoka-v2.devilop.me/home/gia-giay/gia-giay_2.jpg',
    product_thumbnail_three: '',
    product_thumbnail_four: '',
    product_thumbnail_five: '',
    product_thumbnail_six: '',
    product_price: '0',
    category_id: 1
  },
  {
    product_id: "ECOKAPRODUCT",
    product_name: "Storage",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-v2.devilop.me/home/storage-01/storage-01_1.jpg',
    product_thumbnail_two: 'https://ecoka-v2.devilop.me/home/storage-01/storage-01_2.jpg',
    product_thumbnail_three: 'https://ecoka-v2.devilop.me/home/storage-01/storage-01_3.jpg',
    product_thumbnail_four: 'https://ecoka-v2.devilop.me/home/storage-01/storage-01_4.jpg',
    product_thumbnail_five: 'https://ecoka-v2.devilop.me/home/storage-01/storage-01_5.jpg',
    product_thumbnail_six: '',
    product_price: '0',
    category_id: 1
  },
  {
    product_id: "ECOKAPRODUCT",
    product_name: "Storage",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-v2.devilop.me/home/storage-02/storage-02_1.jpg',
    product_thumbnail_two: 'https://ecoka-v2.devilop.me/home/storage-02/storage-02_2.jpg',
    product_thumbnail_three: 'https://ecoka-v2.devilop.me/home/storage-02/storage-02_3.jpg',
    product_thumbnail_four: 'https://ecoka-v2.devilop.me/home/storage-02/storage-02_4.jpg',
    product_thumbnail_five: 'https://ecoka-v2.devilop.me/home/storage-02/storage-02_5.jpg',
    product_thumbnail_six: '',
    product_price: '0',
    category_id: 1
  },
  {
    product_id: "ECOKAPRODUCT",
    product_name: "Storage",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-v2.devilop.me/home/storage-03/storage-03_1.jpg',
    product_thumbnail_two: 'https://ecoka-v2.devilop.me/home/storage-03/storage-03_2.jpg',
    product_thumbnail_three: 'https://ecoka-v2.devilop.me/home/storage-03/storage-03_3.jpg',
    product_thumbnail_four: 'https://ecoka-v2.devilop.me/home/storage-03/storage-03_4.jpg',
    product_thumbnail_five: 'https://ecoka-v2.devilop.me/home/storage-03/storage-03_5.jpg',
    product_thumbnail_six: 'https://ecoka-v2.devilop.me/home/storage-03/storage-03_6.jpg',
    product_price: '0',
    category_id: 1
  },
  // ======================================
  {
    product_id: "ECOKAPRODUCT",
    product_name: "Coster",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-v2.devilop.me/kitchen/coster/coster_1.jpg',
    product_thumbnail_two: 'https://ecoka-v2.devilop.me/kitchen/coster/coster_2.jpg',
    product_thumbnail_three: 'https://ecoka-v2.devilop.me/kitchen/coster/coster_3.jpg',
    product_thumbnail_four: 'https://ecoka-v2.devilop.me/kitchen/coster/coster_4.jpg',
    product_thumbnail_five: 'https://ecoka-v2.devilop.me/kitchen/coster/coster_5.jpg',
    product_thumbnail_six: 'https://ecoka-v2.devilop.me/kitchen/coster/coster_6.jpg',
    product_price: '0',
    category_id: 2
  },
  {
    product_id: "ECOKAPRODUCT",
    product_name: "Holder",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-v2.devilop.me/kitchen/holder/holder.jpg',
    product_thumbnail_two: '',
    product_thumbnail_three: '',
    product_thumbnail_four: '',
    product_thumbnail_five: '',
    product_thumbnail_six: '',
    product_price: '0',
    category_id: 2
  },
  {
    product_id: "ECOKAPRODUCT",
    product_name: "Napkin Ring",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-v2.devilop.me/kitchen/napkin-ring/napkin-ring_1.jpg',
    product_thumbnail_two: 'https://ecoka-v2.devilop.me/kitchen/napkin-ring/napkin-ring_2.jpg',
    product_thumbnail_three: 'https://ecoka-v2.devilop.me/kitchen/napkin-ring/napkin-ring_3.jpg',
    product_thumbnail_four: 'https://ecoka-v2.devilop.me/kitchen/napkin-ring/napkin-ring_4.jpg',
    product_thumbnail_five: 'https://ecoka-v2.devilop.me/kitchen/napkin-ring/napkin-ring_5.jpg',
    product_thumbnail_six: 'https://ecoka-v2.devilop.me/kitchen/napkin-ring/napkin-ring_6.jpg',
    product_price: '0',
    category_id: 2
  },
  {
    product_id: "ECOKAPRODUCT",
    product_name: "Placemat",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-v2.devilop.me/kitchen/placemat-01/placemat-01_1.jpg',
    product_thumbnail_two: 'https://ecoka-v2.devilop.me/kitchen/placemat-01/placemat-01_2.jpg',
    product_thumbnail_three: 'https://ecoka-v2.devilop.me/kitchen/placemat-01/placemat-01_3jpg',
    product_thumbnail_four: 'https://ecoka-v2.devilop.me/kitchen/placemat-01/placemat-01_4.jpg',
    product_thumbnail_five: 'https://ecoka-v2.devilop.me/kitchen/placemat-01/placemat-01_5.jpg',
    product_thumbnail_six: 'https://ecoka-v2.devilop.me/kitchen/placemat-01/placemat-01_6.jpg',
    product_price: '0',
    category_id: 2
  },
  {
    product_id: "ECOKAPRODUCT",
    product_name: "Placemat",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-v2.devilop.me/kitchen/placemat-02/placemat-02_1.jpg',
    product_thumbnail_two: 'https://ecoka-v2.devilop.me/kitchen/placemat-02/placemat-02_2.jpg',
    product_thumbnail_three: 'https://ecoka-v2.devilop.me/kitchen/placemat-02/placemat-02_3jpg',
    product_thumbnail_four: 'https://ecoka-v2.devilop.me/kitchen/placemat-02/placemat-02_4.jpg',
    product_thumbnail_five: 'https://ecoka-v2.devilop.me/kitchen/placemat-02/placemat-02_5.jpg',
    product_thumbnail_six: 'https://ecoka-v2.devilop.me/kitchen/placemat-02/placemat-02_6.jpg',
    product_price: '0',
    category_id: 2
  },
  {
    product_id: "ECOKAPRODUCT",
    product_name: "Placemat",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-v2.devilop.me/kitchen/placemat-03/placemat-03_1.jpg',
    product_thumbnail_two: 'https://ecoka-v2.devilop.me/kitchen/placemat-03/placemat-03_2.jpg',
    product_thumbnail_three: 'https://ecoka-v2.devilop.me/kitchen/placemat-03/placemat-03_3jpg',
    product_thumbnail_four: 'https://ecoka-v2.devilop.me/kitchen/placemat-03/placemat-03_4.jpg',
    product_thumbnail_five: 'https://ecoka-v2.devilop.me/kitchen/placemat-03/placemat-03_5.jpg',
    product_thumbnail_six: '',
    product_price: '0',
    category_id: 2
  },
  // ======================================
  {
    product_id: "ECOKAPRODUCT",
    product_name: "Benches",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-v2.devilop.me/furniture/benches/benches.jpg',
    product_thumbnail_two: '',
    product_thumbnail_three: '',
    product_thumbnail_four: '',
    product_thumbnail_five: '',
    product_thumbnail_six: '',
    product_price: '0',
    category_id: 3
  },
  {
    product_id: "ECOKAPRODUCT",
    product_name: "Bộ Sofa",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-v2.devilop.me/furniture/bo-sofa/bo-sofa.jpg',
    product_thumbnail_two: '',
    product_thumbnail_three: '',
    product_thumbnail_four: '',
    product_thumbnail_five: '',
    product_thumbnail_six: '',
    product_price: '0',
    category_id: 3
  },
  {
    product_id: "ECOKAPRODUCT",
    product_name: "Chair",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-v2.devilop.me/furniture/chair/chair.jpg',
    product_thumbnail_two: '',
    product_thumbnail_three: '',
    product_thumbnail_four: '',
    product_thumbnail_five: '',
    product_thumbnail_six: '',
    product_price: '0',
    category_id: 3
  },
  {
    product_id: "ECOKAPRODUCT",
    product_name: "Coffee Table",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-v2.devilop.me/furniture/coffee-table/coffee-table.jpg',
    product_thumbnail_two: '',
    product_thumbnail_three: '',
    product_thumbnail_four: '',
    product_thumbnail_five: '',
    product_thumbnail_six: '',
    product_price: '0',
    category_id: 3
  },
  {
    product_id: "ECOKAPRODUCT",
    product_name: "Đôn",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-v2.devilop.me/furniture/don/don_1.jpg',
    product_thumbnail_two: 'https://ecoka-v2.devilop.me/furniture/don/don_2.jpg',
    product_thumbnail_three: '',
    product_thumbnail_four: '',
    product_thumbnail_five: '',
    product_thumbnail_six: '',
    product_price: '0',
    category_id: 3
  },
  {
    product_id: "ECOKAPRODUCT",
    product_name: "Home Storage",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-v2.devilop.me/furniture/home-storage/home-storage_1.jpg',
    product_thumbnail_two: 'https://ecoka-v2.devilop.me/furniture/home-storage/home-storage_2.jpg',
    product_thumbnail_three: 'https://ecoka-v2.devilop.me/furniture/home-storage/home-storage_3.jpg',
    product_thumbnail_four: '',
    product_thumbnail_five: '',
    product_thumbnail_six: '',
    product_price: '0',
    category_id: 3
  },
  {
    product_id: "ECOKAPRODUCT",
    product_name: "Sofa",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-v2.devilop.me/furniture/sofa/sofa.jpg',
    product_thumbnail_two: '',
    product_thumbnail_three: '',
    product_thumbnail_four: '',
    product_thumbnail_five: '',
    product_thumbnail_six: '',
    product_price: '0',
    category_id: 3
  },
  {
    product_id: "ECOKAPRODUCT",
    product_name: "Sofa Table",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-v2.devilop.me/furniture/sofa-table/sofa-table_1.jpg',
    product_thumbnail_two: 'https://ecoka-v2.devilop.me/furniture/sofa-table/sofa-table_2.jpg',
    product_thumbnail_three: 'https://ecoka-v2.devilop.me/furniture/sofa-table/sofa-table_3.jpg',
    product_thumbnail_four: 'https://ecoka-v2.devilop.me/furniture/sofa-table/sofa-table_4.jpg',
    product_thumbnail_five: 'https://ecoka-v2.devilop.me/furniture/sofa-table/sofa-table_5.jpg',
    product_thumbnail_six: 'https://ecoka-v2.devilop.me/furniture/sofa-table/sofa-table_6.jpg',
    product_price: '0',
    category_id: 3
  },
  {
    product_id: "ECOKAPRODUCT",
    product_name: "Sofa Table Restangle",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-v2.devilop.me/furniture/sofa-table-restangle/sofa-table-restangle.jpg',
    product_thumbnail_two: '',
    product_thumbnail_three: '',
    product_thumbnail_four: '',
    product_thumbnail_five: '',
    product_thumbnail_six: '',
    product_price: '0',
    category_id: 3
  },
  {
    product_id: "ECOKAPRODUCT",
    product_name: "Tủ Kệ",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-v2.devilop.me/furniture/tu-ke/tu-ke_1.jpg',
    product_thumbnail_two: 'https://ecoka-v2.devilop.me/furniture/tu-ke/tu-ke_2.jpg',
    product_thumbnail_three: 'https://ecoka-v2.devilop.me/furniture/tu-ke/tu-ke_3.jpg',
    product_thumbnail_four: 'https://ecoka-v2.devilop.me/furniture/tu-ke/tu-ke_4.jpg',
    product_thumbnail_five: '',
    product_thumbnail_six: '',
    product_price: '0',
    category_id: 3
  },
];

export const FAKE = {
  CATEGORIES,
  BLOGS,
  PRODUCTS,
  HOME_PRODUCTS
};
