const PRODUCT_KITCHEN = [
  {
    product_id: "ECOKA-PRODUCT-01",
    product_name_vi: "Nhẫn Lục Bình",
    product_name_en: '',
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-home.devilop.me/home/01/01_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-home.devilop.me/home/01/01_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-home.devilop.me/home/01/01_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-home.devilop.me/home/01/01_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-home.devilop.me/home/01/01_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-home.devilop.me/home/01/01_6.jpg',
    category: 'KITCHEN'
  },
  {
    product_id: "ECOKA-PRODUCT-09",
    product_name_vi: "Giỏ Tre",
    product_name_en: '',
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-kitchen.devilop.me/kitchen/09/09_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-kitchen.devilop.me/kitchen/09/09_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-kitchen.devilop.me/kitchen/09/09_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-kitchen.devilop.me/kitchen/09/09_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-kitchen.devilop.me/kitchen/09/09_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-kitchen.devilop.me/kitchen/09/09_6.jpg',
    category: 'KITCHEN'
  },
  {
    product_id: "ECOKA-PRODUCT-10",
    product_name_vi: "Lót Ly Lục Bình",
    product_name_en: '',
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-kitchen.devilop.me/kitchen/10/10_1.JPG',
    product_thumbnail_two: 'https://ecoka-product-kitchen.devilop.me/kitchen/10/10_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-kitchen.devilop.me/kitchen/10/10_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-kitchen.devilop.me/kitchen/10/10_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-kitchen.devilop.me/kitchen/10/10_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-kitchen.devilop.me/kitchen/10/10_6.jpg',
    category: 'KITCHEN'
  },
  {
    product_id: "ECOKA-PRODUCT-11",
    product_name_vi: "Lót Ly Macrame",
    product_name_en: '',
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-kitchen.devilop.me/kitchen/11/11_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-kitchen.devilop.me/kitchen/11/11_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-kitchen.devilop.me/kitchen/11/11_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-kitchen.devilop.me/kitchen/11/11_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-kitchen.devilop.me/kitchen/11/11_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-kitchen.devilop.me/kitchen/11/11_6.jpg',
    category: 'KITCHEN'
  },
  {
    product_id: "ECOKA-PRODUCT-12",
    product_name_vi: "Giỏ Đựng Macrame 30cm-Beige",
    product_name_en: '',
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-kitchen.devilop.me/kitchen/12/12_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-kitchen.devilop.me/kitchen/12/12_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-kitchen.devilop.me/kitchen/12/12_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-kitchen.devilop.me/kitchen/12/12_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-kitchen.devilop.me/kitchen/12/12_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-kitchen.devilop.me/kitchen/12/12_6.jpg',
    category: 'KITCHEN'
  },
  {
    product_id: "ECOKA-PRODUCT-13",
    product_name_vi: "Giỏ Đựng Macrame 30cm-Socola",
    product_name_en: '',
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-kitchen.devilop.me/kitchen/13/13_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-kitchen.devilop.me/kitchen/13/13_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-kitchen.devilop.me/kitchen/13/13_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-kitchen.devilop.me/kitchen/13/13_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-kitchen.devilop.me/kitchen/13/13_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-kitchen.devilop.me/kitchen/13/13_6.jpg',
    category: 'KITCHEN'
  },
  {
    product_id: "ECOKA-PRODUCT-14",
    product_name_vi: "Giỏ Đựng Cỏ Biển Vuông 30cm",
    product_name_en: '',
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-kitchen.devilop.me/kitchen/14/14_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-kitchen.devilop.me/kitchen/14/14_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-kitchen.devilop.me/kitchen/14/14_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-kitchen.devilop.me/kitchen/14/14_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-kitchen.devilop.me/kitchen/14/14_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-kitchen.devilop.me/kitchen/14/14_6.jpg',
    category: 'KITCHEN'
  },
  {
    product_id: "ECOKA-PRODUCT-15",
    product_name_vi: "Giỏ Đựng Lục Bình Có Lỗ 3",
    product_name_en: '',
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-kitchen.devilop.me/kitchen/15/15_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-kitchen.devilop.me/kitchen/15/15_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-kitchen.devilop.me/kitchen/15/15_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-kitchen.devilop.me/kitchen/15/15_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-kitchen.devilop.me/kitchen/15/15_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-kitchen.devilop.me/kitchen/15/15_6.jpg',
    category: 'KITCHEN'
  },
  {
    product_id: "ECOKA-PRODUCT-16",
    product_name_vi: "Giỏ Đựng Lục Bình Xca Set 3",
    product_name_en: '',
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-kitchen.devilop.me/kitchen/16/16_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-kitchen.devilop.me/kitchen/16/16_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-kitchen.devilop.me/kitchen/16/16_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-kitchen.devilop.me/kitchen/16/16_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-kitchen.devilop.me/kitchen/16/16_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-kitchen.devilop.me/kitchen/16/16_6.jpg',
    category: 'KITCHEN'
  },
  {
    product_id: "ECOKA-PRODUCT-17",
    product_name_vi: "Bộ Lục Bình Trữ Nước 3-SF",
    product_name_en: '',
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-kitchen.devilop.me/kitchen/17/17_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-kitchen.devilop.me/kitchen/17/17_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-kitchen.devilop.me/kitchen/17/17_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-kitchen.devilop.me/kitchen/17/17_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-kitchen.devilop.me/kitchen/17/17_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-kitchen.devilop.me/kitchen/17/17_6.jpg',
    category: 'KITCHEN'
  },
  {
    product_id: "ECOKA-PRODUCT-18",
    product_name_vi: "Bình Lục Bình Vuông 30cm",
    product_name_en: '',
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-kitchen.devilop.me/kitchen/18/18_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-kitchen.devilop.me/kitchen/18/18_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-kitchen.devilop.me/kitchen/18/18_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-kitchen.devilop.me/kitchen/18/18_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-kitchen.devilop.me/kitchen/18/18_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-kitchen.devilop.me/kitchen/18/18_6.jpg',
    category: 'KITCHEN'
  },
  {
    product_id: "ECOKA-PRODUCT-43",
    product_name_vi: "Coster",
    product_name_en: '',
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-v2.devilop.me/kitchen/coster/coster_1.jpg',
    product_thumbnail_two: 'https://ecoka-v2.devilop.me/kitchen/coster/coster_2.jpg',
    product_thumbnail_three: 'https://ecoka-v2.devilop.me/kitchen/coster/coster_3.jpg',
    product_thumbnail_four: 'https://ecoka-v2.devilop.me/kitchen/coster/coster_4.jpg',
    product_thumbnail_five: 'https://ecoka-v2.devilop.me/kitchen/coster/coster_5.jpg',
    product_thumbnail_six: 'https://ecoka-v2.devilop.me/kitchen/coster/coster_6.jpg',
    category: 'KITCHEN'
  },
  {
    product_id: "ECOKA-PRODUCT-44",
    product_name_vi: "Holder",
    product_name_en: '',
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-v2.devilop.me/kitchen/holder/holder.jpg',
    product_thumbnail_two: '',
    product_thumbnail_three: '',
    product_thumbnail_four: '',
    product_thumbnail_five: '',
    product_thumbnail_six: '',
    category: 'KITCHEN'
  },
  {
    product_id: "ECOKA-PRODUCT-45",
    product_name_vi: "Napkin Ring",
    product_name_en: '',
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-v2.devilop.me/kitchen/napkin-ring/napkin-ring_1.jpg',
    product_thumbnail_two: 'https://ecoka-v2.devilop.me/kitchen/napkin-ring/napkin-ring_2.jpg',
    product_thumbnail_three: 'https://ecoka-v2.devilop.me/kitchen/napkin-ring/napkin-ring_3.jpg',
    product_thumbnail_four: 'https://ecoka-v2.devilop.me/kitchen/napkin-ring/napkin-ring_4.jpg',
    product_thumbnail_five: 'https://ecoka-v2.devilop.me/kitchen/napkin-ring/napkin-ring_5.jpg',
    product_thumbnail_six: 'https://ecoka-v2.devilop.me/kitchen/napkin-ring/napkin-ring_6.jpg',
    category: 'KITCHEN'
  },
  {
    product_id: "ECOKA-PRODUCT-46",
    product_name_vi: "Placemat",
    product_name_en: '',
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-v2.devilop.me/kitchen/placemat-01/placemat-01_1.jpg',
    product_thumbnail_two: 'https://ecoka-v2.devilop.me/kitchen/placemat-01/placemat-01_2.jpg',
    product_thumbnail_three: 'https://ecoka-v2.devilop.me/kitchen/placemat-01/placemat-01_3jpg',
    product_thumbnail_four: 'https://ecoka-v2.devilop.me/kitchen/placemat-01/placemat-01_4.jpg',
    product_thumbnail_five: 'https://ecoka-v2.devilop.me/kitchen/placemat-01/placemat-01_5.jpg',
    product_thumbnail_six: 'https://ecoka-v2.devilop.me/kitchen/placemat-01/placemat-01_6.jpg',
    category: 'KITCHEN'
  },
  {
    product_id: "ECOKA-PRODUCT-47",
    product_name_vi: "Placemat",
    product_name_en: '',
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-v2.devilop.me/kitchen/placemat-02/placemat-02_1.jpg',
    product_thumbnail_two: 'https://ecoka-v2.devilop.me/kitchen/placemat-02/placemat-02_2.jpg',
    product_thumbnail_three: 'https://ecoka-v2.devilop.me/kitchen/placemat-02/placemat-02_3jpg',
    product_thumbnail_four: 'https://ecoka-v2.devilop.me/kitchen/placemat-02/placemat-02_4.jpg',
    product_thumbnail_five: 'https://ecoka-v2.devilop.me/kitchen/placemat-02/placemat-02_5.jpg',
    product_thumbnail_six: 'https://ecoka-v2.devilop.me/kitchen/placemat-02/placemat-02_6.jpg',
    category: 'KITCHEN'
  },
  {
    product_id: "ECOKA-PRODUCT-48",
    product_name_vi: "Placemat",
    product_name_en: '',
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-v2.devilop.me/kitchen/placemat-03/placemat-03_1.jpg',
    product_thumbnail_two: 'https://ecoka-v2.devilop.me/kitchen/placemat-03/placemat-03_2.jpg',
    product_thumbnail_three: 'https://ecoka-v2.devilop.me/kitchen/placemat-03/placemat-03_3jpg',
    product_thumbnail_four: 'https://ecoka-v2.devilop.me/kitchen/placemat-03/placemat-03_4.jpg',
    product_thumbnail_five: 'https://ecoka-v2.devilop.me/kitchen/placemat-03/placemat-03_5.jpg',
    product_thumbnail_six: '',
    category: 'KITCHEN'
  },
];