const PRODUCT_HOME = [
  {
    product_id: "ECOKA-PRODUCT-02",
    product_name_vi: "Thảm Cỏ Biển Hoa 4ft",
    product_name_en: '',
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-home.devilop.me/home/02/02_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-home.devilop.me/home/02/02_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-home.devilop.me/home/02/02_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-home.devilop.me/home/02/02_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-home.devilop.me/home/02/02_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-home.devilop.me/home/02/02_6.jpg',
    category: 'HOME'
  },
  {
    product_id: "ECOKA-PRODUCT-03",
    product_name_vi: "Thảm Cỏ Biển 3ft",
    product_name_en: '',
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-home.devilop.me/home/03/03_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-home.devilop.me/home/03/03_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-home.devilop.me/home/03/03_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-home.devilop.me/home/03/03_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-home.devilop.me/home/03/03_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-home.devilop.me/home/03/03_6.jpg',
    category: 'HOME'
  },
  {
    product_id: "ECOKA-PRODUCT-04",
    product_name_vi: "Rèm Macrame-Màu Be",
    product_name_en: '',
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-home.devilop.me/home/04/04_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-home.devilop.me/home/04/04_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-home.devilop.me/home/04/04_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-home.devilop.me/home/04/04_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-home.devilop.me/home/04/04_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-home.devilop.me/home/04/04_6.jpg',
    category: 'HOME'
  },
  {
    product_id: "ECOKA-PRODUCT-05",
    product_name_vi: "Rèm Macrame-Vàng",
    product_name_en: '',
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-home.devilop.me/home/05/05_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-home.devilop.me/home/05/05_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-home.devilop.me/home/05/05_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-home.devilop.me/home/05/05_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-home.devilop.me/home/05/05_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-home.devilop.me/home/05/05_6.jpg',
    category: 'HOME'
  },
  {
    product_id: "ECOKA-PRODUCT-06",
    product_name_vi: "Rèm Macrame-Xám",
    product_name_en: '',
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-home.devilop.me/home/06/06_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-home.devilop.me/home/06/06_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-home.devilop.me/home/06/06_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-home.devilop.me/home/06/06_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-home.devilop.me/home/06/06_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-home.devilop.me/home/06/06_6.jpg',
    category: 'HOME'
  },
  {
    product_id: "ECOKA-PRODUCT-07",
    product_name_vi: "Rèm Macrarme-Nâu Hồng",
    product_name_en: '',
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-home.devilop.me/home/07/07_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-home.devilop.me/home/07/07_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-home.devilop.me/home/07/07_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-home.devilop.me/home/07/07_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-home.devilop.me/home/07/07_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-home.devilop.me/home/07/07_6.jpg',
    category: 'HOME'
  },
  {
    product_id: "ECOKA-PRODUCT-08",
    product_name_vi: "Rèm Lưới",
    product_name_en: '',
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-home.devilop.me/home/08/08_1.png',
    product_thumbnail_two: 'https://ecoka-product-home.devilop.me/home/08/08_2.png',
    product_thumbnail_three: 'https://ecoka-product-home.devilop.me/home/08/08_3.png',
    product_thumbnail_four: 'https://ecoka-product-home.devilop.me/home/08/08_4.png',
    product_thumbnail_five: 'https://ecoka-product-home.devilop.me/home/08/08_5.png',
    product_thumbnail_six: 'https://ecoka-product-home.devilop.me/home/08/08_6.png',
    category: 'HOME'
  },
  {
    product_id: "ECOKA-PRODUCT-39",
    product_name_vi: "Giá Giày",
    product_name_en: '',
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-v2.devilop.me/home/gia-giay/gia-giay_1.jpg',
    product_thumbnail_two: 'https://ecoka-v2.devilop.me/home/gia-giay/gia-giay_2.jpg',
    product_thumbnail_three: '',
    product_thumbnail_four: '',
    product_thumbnail_five: '',
    product_thumbnail_six: '',
    category: 'HOME'
  },
  {
    product_id: "ECOKA-PRODUCT-40",
    product_name_vi: "Sọt Đựng",
    product_name_en: '',
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-v2.devilop.me/home/storage-01/storage-01_1.jpg',
    product_thumbnail_two: 'https://ecoka-v2.devilop.me/home/storage-01/storage-01_2.jpg',
    product_thumbnail_three: 'https://ecoka-v2.devilop.me/home/storage-01/storage-01_3.jpg',
    product_thumbnail_four: 'https://ecoka-v2.devilop.me/home/storage-01/storage-01_4.jpg',
    product_thumbnail_five: 'https://ecoka-v2.devilop.me/home/storage-01/storage-01_5.jpg',
    product_thumbnail_six: '',
    category: 'HOME'
  },
  {
    product_id: "ECOKA-PRODUCT-41",
    product_name_vi: "Sọt Đựng",
    product_name_en: '',
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-v2.devilop.me/home/storage-02/storage-02_1.jpg',
    product_thumbnail_two: 'https://ecoka-v2.devilop.me/home/storage-02/storage-02_2.jpg',
    product_thumbnail_three: 'https://ecoka-v2.devilop.me/home/storage-02/storage-02_3.jpg',
    product_thumbnail_four: 'https://ecoka-v2.devilop.me/home/storage-02/storage-02_4.jpg',
    product_thumbnail_five: 'https://ecoka-v2.devilop.me/home/storage-02/storage-02_5.jpg',
    product_thumbnail_six: '',
    category: 'HOME'
  },
  {
    product_id: "ECOKA-PRODUCT-42",
    product_name_vi: "Sọt Đựng",
    product_name_en: '',
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-v2.devilop.me/home/storage-03/storage-03_1.jpg',
    product_thumbnail_two: 'https://ecoka-v2.devilop.me/home/storage-03/storage-03_2.jpg',
    product_thumbnail_three: 'https://ecoka-v2.devilop.me/home/storage-03/storage-03_3.jpg',
    product_thumbnail_four: 'https://ecoka-v2.devilop.me/home/storage-03/storage-03_4.jpg',
    product_thumbnail_five: 'https://ecoka-v2.devilop.me/home/storage-03/storage-03_5.jpg',
    product_thumbnail_six: 'https://ecoka-v2.devilop.me/home/storage-03/storage-03_6.jpg',
    category: 'HOME'
  },
];