const PRODUCT_FURNITURE = [
  {
    product_id: "ECOKA-PRODUCT-49",
    product_name_vi: "Benches",
    product_name_en: '',
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-v2.devilop.me/furniture/benches/benches.jpg',
    product_thumbnail_two: '',
    product_thumbnail_three: '',
    product_thumbnail_four: '',
    product_thumbnail_five: '',
    product_thumbnail_six: '',
    category: 'FURNITURE'
  },
  {
    product_id: "ECOKA-PRODUCT-50",
    product_name_vi: "Bộ Sofa",
    product_name_en: '',
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-v2.devilop.me/furniture/bo-sofa/bo-sofa.jpg',
    product_thumbnail_two: '',
    product_thumbnail_three: '',
    product_thumbnail_four: '',
    product_thumbnail_five: '',
    product_thumbnail_six: '',
    category: 'FURNITURE'
  },
  {
    product_id: "ECOKA-PRODUCT-51",
    product_name_vi: "Chair",
    product_name_en: '',
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-v2.devilop.me/furniture/chair/chair.jpg',
    product_thumbnail_two: '',
    product_thumbnail_three: '',
    product_thumbnail_four: '',
    product_thumbnail_five: '',
    product_thumbnail_six: '',
    category: 'FURNITURE'
  },
  {
    product_id: "ECOKA-PRODUCT-52",
    product_name_vi: "Coffee Table",
    product_name_en: '',
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-v2.devilop.me/furniture/coffee-table/coffee-table.jpg',
    product_thumbnail_two: '',
    product_thumbnail_three: '',
    product_thumbnail_four: '',
    product_thumbnail_five: '',
    product_thumbnail_six: '',
    category: 'FURNITURE'
  },
  {
    product_id: "ECOKA-PRODUCT-53",
    product_name_vi: "Đôn",
    product_name_en: '',
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-v2.devilop.me/furniture/don/don_1.jpg',
    product_thumbnail_two: 'https://ecoka-v2.devilop.me/furniture/don/don_2.jpg',
    product_thumbnail_three: '',
    product_thumbnail_four: '',
    product_thumbnail_five: '',
    product_thumbnail_six: '',
    category: 'FURNITURE'
  },
  {
    product_id: "ECOKA-PRODUCT-54",
    product_name_vi: "Home Storage",
    product_name_en: '',
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-v2.devilop.me/furniture/home-storage/home-storage_1.jpg',
    product_thumbnail_two: 'https://ecoka-v2.devilop.me/furniture/home-storage/home-storage_2.jpg',
    product_thumbnail_three: 'https://ecoka-v2.devilop.me/furniture/home-storage/home-storage_3.jpg',
    product_thumbnail_four: '',
    product_thumbnail_five: '',
    product_thumbnail_six: '',
    category: 'FURNITURE'
  },
  {
    product_id: "ECOKA-PRODUCT-55",
    product_name_vi: "Sofa",
    product_name_en: '',
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-v2.devilop.me/furniture/sofa/sofa.jpg',
    product_thumbnail_two: '',
    product_thumbnail_three: '',
    product_thumbnail_four: '',
    product_thumbnail_five: '',
    product_thumbnail_six: '',
    category: 'FURNITURE'
  },
  {
    product_id: "ECOKA-PRODUCT-56",
    product_name_vi: "Sofa Table",
    product_name_en: '',
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-v2.devilop.me/furniture/sofa-table/sofa-table_1.jpg',
    product_thumbnail_two: 'https://ecoka-v2.devilop.me/furniture/sofa-table/sofa-table_2.jpg',
    product_thumbnail_three: 'https://ecoka-v2.devilop.me/furniture/sofa-table/sofa-table_3.jpg',
    product_thumbnail_four: 'https://ecoka-v2.devilop.me/furniture/sofa-table/sofa-table_4.jpg',
    product_thumbnail_five: 'https://ecoka-v2.devilop.me/furniture/sofa-table/sofa-table_5.jpg',
    product_thumbnail_six: 'https://ecoka-v2.devilop.me/furniture/sofa-table/sofa-table_6.jpg',
    category: 'FURNITURE'
  },
  {
    product_id: "ECOKA-PRODUCT-57",
    product_name_vi: "Sofa Table Restangle",
    product_name_en: '',
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-v2.devilop.me/furniture/sofa-table-restangle/sofa-table-restangle.jpg',
    product_thumbnail_two: '',
    product_thumbnail_three: '',
    product_thumbnail_four: '',
    product_thumbnail_five: '',
    product_thumbnail_six: '',
    category: 'FURNITURE'
  },
  {
    product_id: "ECOKA-PRODUCT-58",
    product_name_vi: "Tủ Kệ",
    product_name_en: '',
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-v2.devilop.me/furniture/tu-ke/tu-ke_1.jpg',
    product_thumbnail_two: 'https://ecoka-v2.devilop.me/furniture/tu-ke/tu-ke_2.jpg',
    product_thumbnail_three: 'https://ecoka-v2.devilop.me/furniture/tu-ke/tu-ke_3.jpg',
    product_thumbnail_four: 'https://ecoka-v2.devilop.me/furniture/tu-ke/tu-ke_4.jpg',
    product_thumbnail_five: '',
    product_thumbnail_six: '',
    category: 'FURNITURE'
  },
];