const PRODUCT_FASHION = [
  {
    product_id: "ECOKA-PRODUCT-19",
    product_name_vi: "Túi 3 Tinh - Vàng Hồng Đỏ",
    product_name_en: '',
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-fashion.devilop.me/fashion/19/19_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-fashion.devilop.me/fashion/19/19_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-fashion.devilop.me/fashion/19/19_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-fashion.devilop.me/fashion/19/19_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-fashion.devilop.me/fashion/19/19_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-fashion.devilop.me/fashion/19/19_6.jpg',
    category: 'FASHION'
  },
  {
    product_id: "ECOKA-PRODUCT-20",
    product_name_vi: "Túi 3 Màu - Vàng Nâu",
    product_name_en: '',
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-fashion.devilop.me/fashion/20/20_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-fashion.devilop.me/fashion/20/20_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-fashion.devilop.me/fashion/20/20_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-fashion.devilop.me/fashion/20/20_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-fashion.devilop.me/fashion/20/20_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-fashion.devilop.me/fashion/20/20_6.jpg',
    category: 'FASHION'
  },
  {
    product_id: "ECOKA-PRODUCT-21",
    product_name_vi: "Túi 3 Màu - Màu Trắng Nâu",
    product_name_en: '',
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-fashion.devilop.me/fashion/21/21_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-fashion.devilop.me/fashion/21/21_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-fashion.devilop.me/fashion/21/21_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-fashion.devilop.me/fashion/21/21_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-fashion.devilop.me/fashion/21/21_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-fashion.devilop.me/fashion/21/21_6.jpg',
    category: 'FASHION'
  },
  {
    product_id: "ECOKA-PRODUCT-22",
    product_name_vi: "Túi Cói Kem",
    product_name_en: '',
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-fashion.devilop.me/fashion/22/22_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-fashion.devilop.me/fashion/22/22_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-fashion.devilop.me/fashion/22/22_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-fashion.devilop.me/fashion/22/22_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-fashion.devilop.me/fashion/22/22_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-fashion.devilop.me/fashion/22/22_6.jpg',
    category: 'FASHION'
  },
  {
    product_id: "ECOKA-PRODUCT-23",
    product_name_vi: "Túi Cói MixColor",
    product_name_en: '',
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-fashion.devilop.me/fashion/23/23_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-fashion.devilop.me/fashion/23/23_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-fashion.devilop.me/fashion/23/23_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-fashion.devilop.me/fashion/23/23_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-fashion.devilop.me/fashion/23/23_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-fashion.devilop.me/fashion/23/23_6.jpg',
    category: 'FASHION'
  },
  {
    product_id: "ECOKA-PRODUCT-24",
    product_name_vi: "Túc Lục Bình",
    product_name_en: '',
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-fashion.devilop.me/fashion/24/24_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-fashion.devilop.me/fashion/24/24_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-fashion.devilop.me/fashion/24/24_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-fashion.devilop.me/fashion/24/24_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-fashion.devilop.me/fashion/24/24_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-fashion.devilop.me/fashion/24/24_6.jpg',
    category: 'FASHION'
  },
  {
    product_id: "ECOKA-PRODUCT-25",
    product_name_vi: "Túi Lục Bình Chim Công",
    product_name_en: '',
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-fashion.devilop.me/fashion/25/25_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-fashion.devilop.me/fashion/25/25_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-fashion.devilop.me/fashion/25/25_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-fashion.devilop.me/fashion/25/25_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-fashion.devilop.me/fashion/25/25_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-fashion.devilop.me/fashion/25/25_6.jpg',
    category: 'FASHION'
  },
  {
    product_id: "ECOKA-PRODUCT-26",
    product_name_vi: "Túi Lục Bình Hoa Độc",
    product_name_en: '',
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-fashion.devilop.me/fashion/26/26_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-fashion.devilop.me/fashion/26/26_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-fashion.devilop.me/fashion/26/26_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-fashion.devilop.me/fashion/26/26_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-fashion.devilop.me/fashion/26/26_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-fashion.devilop.me/fashion/26/26_6.jpg',
    category: 'FASHION'
  },
  {
    product_id: "ECOKA-PRODUCT-27",
    product_name_vi: "Túi Lục Bình Hoa Miếng",
    product_name_en: '',
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-fashion.devilop.me/fashion/27/27_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-fashion.devilop.me/fashion/27/27_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-fashion.devilop.me/fashion/27/27_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-fashion.devilop.me/fashion/27/27_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-fashion.devilop.me/fashion/27/27_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-fashion.devilop.me/fashion/27/27_6.jpg',
    category: 'FASHION'
  },
  {
    product_id: "ECOKA-PRODUCT-28",
    product_name_vi: "Túi Lục Bình Quay Đá 26",
    product_name_en: '',
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-fashion.devilop.me/fashion/28/28_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-fashion.devilop.me/fashion/28/28_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-fashion.devilop.me/fashion/28/28_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-fashion.devilop.me/fashion/28/28_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-fashion.devilop.me/fashion/28/28_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-fashion.devilop.me/fashion/28/28_6.jpg',
    category: 'FASHION'
  },
  {
    product_id: "ECOKA-PRODUCT-29",
    product_name_vi: "Túi Lục Bình Quay Đà",
    product_name_en: '',
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-fashion.devilop.me/fashion/29/29_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-fashion.devilop.me/fashion/29/29_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-fashion.devilop.me/fashion/29/29_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-fashion.devilop.me/fashion/29/29_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-fashion.devilop.me/fashion/29/29_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-fashion.devilop.me/fashion/29/29_6.jpg',
    category: 'FASHION'
  },
  {
    product_id: "ECOKA-PRODUCT-30",
    product_name_vi: "Túi Lục Bình Quay Da Macrame",
    product_name_en: '',
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-fashion.devilop.me/fashion/30/30_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-fashion.devilop.me/fashion/30/30_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-fashion.devilop.me/fashion/30/30_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-fashion.devilop.me/fashion/30/30_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-fashion.devilop.me/fashion/30/30_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-fashion.devilop.me/fashion/30/30_6.jpg',
    category: 'FASHION'
  },
  {
    product_id: "ECOKA-PRODUCT-31",
    product_name_vi: "Túi Macrame Điện Thoại - Hồng",
    product_name_en: '',
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-fashion.devilop.me/fashion/31/31_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-fashion.devilop.me/fashion/31/31_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-fashion.devilop.me/fashion/31/31_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-fashion.devilop.me/fashion/31/31_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-fashion.devilop.me/fashion/31/31_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-fashion.devilop.me/fashion/31/31_6.jpg',
    category: 'FASHION'
  },
  {
    product_id: "ECOKA-PRODUCT-32",
    product_name_vi: "Túi Macrame Điện Thoại - Kem",
    product_name_en: '',
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-fashion.devilop.me/fashion/32/32_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-fashion.devilop.me/fashion/32/32_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-fashion.devilop.me/fashion/32/32_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-fashion.devilop.me/fashion/32/32_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-fashion.devilop.me/fashion/32/32_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-fashion.devilop.me/fashion/32/32_6.jpg',
    category: 'FASHION'
  },
  {
    product_id: "ECOKA-PRODUCT-33",
    product_name_vi: "Túi Macrame Laptop 32",
    product_name_en: '',
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-fashion.devilop.me/fashion/33/33_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-fashion.devilop.me/fashion/33/33_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-fashion.devilop.me/fashion/33/33_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-fashion.devilop.me/fashion/33/33_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-fashion.devilop.me/fashion/33/33_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-fashion.devilop.me/fashion/33/33_6.jpg',
    category: 'FASHION'
  },
  {
    product_id: "ECOKA-PRODUCT-34",
    product_name_vi: "Túi Macrame Ngang - Kem",
    product_name_en: '',
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/34/34_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/34/34_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/34/34_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/34/34_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/34/34_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/34/34_6.jpg',
    category: 'FASHION'
  },
  {
    product_id: "ECOKA-PRODUCT-35",
    product_name_vi: "Túi Trống - Kem Nâu",
    product_name_en: '',
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/35/35_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/35/35_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/35/35_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/35/35_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/35/35_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/35/35_6.jpg',
    category: 'FASHION'
  },
  {
    product_id: "ECOKA-PRODUCT-36",
    product_name_vi: "Túi Trống - Kem Vàng",
    product_name_en: '',
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/36/36_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/36/36_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/36/36_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/36/36_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/36/36_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/36/36_6.jpg',
    category: 'FASHION'
  },
  {
    product_id: "ECOKA-PRODUCT-37",
    product_name_vi: "Mũ Đi Biển Hoa Lục Bình Cho Nữ Sang Trọng",
    product_name_en: '',
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/37/37_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/37/37_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/37/37_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/37/37_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/37/37_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/37/37_6.jpg',
    category: 'FASHION'
  },
  {
    product_id: "ECOKA-PRODUCT-38",
    product_name_vi: "Mũ Đi Biển Lục Bình Dây Đơn Cho Nữ",
    product_name_en: '',
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/38/38_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/38/38_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/38/38_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/38/38_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/38/38_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/38/38_6.jpg',
    category: 'FASHION'
  },
];