const PRODUCTS = [
  {
    product_id: "ECOKAPRODUCT01",
    product_name: "Nhẫn Lục Bình",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-home.devilop.me/home/01/01_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-home.devilop.me/home/01/01_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-home.devilop.me/home/01/01_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-home.devilop.me/home/01/01_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-home.devilop.me/home/01/01_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-home.devilop.me/home/01/01_6.jpg',
    product_price: '0',
    category_id: 2
  },
  {
    product_id: "ECOKAPRODUCT02",
    product_name: "Thảm Cỏ Biển Hoa 4ft",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-home.devilop.me/home/02/02_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-home.devilop.me/home/02/02_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-home.devilop.me/home/02/02_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-home.devilop.me/home/02/02_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-home.devilop.me/home/02/02_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-home.devilop.me/home/02/02_6.jpg',
    product_price: '0',
    category_id: 1
  },
  {
    product_id: "ECOKAPRODUCT03",
    product_name: "Thảm Cỏ Biển 3ft",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-home.devilop.me/home/03/03_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-home.devilop.me/home/03/03_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-home.devilop.me/home/03/03_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-home.devilop.me/home/03/03_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-home.devilop.me/home/03/03_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-home.devilop.me/home/03/03_6.jpg',
    product_price: '0',
    category_id: 1
  },
  {
    product_id: "ECOKAPRODUCT04",
    product_name: "Rèm Macrame-Màu Be",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-home.devilop.me/home/04/04_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-home.devilop.me/home/04/04_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-home.devilop.me/home/04/04_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-home.devilop.me/home/04/04_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-home.devilop.me/home/04/04_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-home.devilop.me/home/04/04_6.jpg',
    product_price: '0',
    category_id: 1
  },
  {
    product_id: "ECOKAPRODUCT05",
    product_name: "Rèm Macrame-Vàng",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-home.devilop.me/home/05/05_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-home.devilop.me/home/05/05_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-home.devilop.me/home/05/05_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-home.devilop.me/home/05/05_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-home.devilop.me/home/05/05_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-home.devilop.me/home/05/05_6.jpg',
    product_price: '0',
    category_id: 1
  },
  {
    product_id: "ECOKAPRODUCT06",
    product_name: "Rèm Macrame-Xám",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-home.devilop.me/home/06/06_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-home.devilop.me/home/06/06_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-home.devilop.me/home/06/06_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-home.devilop.me/home/06/06_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-home.devilop.me/home/06/06_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-home.devilop.me/home/06/06_6.jpg',
    product_price: '0',
    category_id: 1
  },
  {
    product_id: "ECOKAPRODUCT07",
    product_name: "Rèm Macrarme-Nâu Hồng",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-home.devilop.me/home/07/07_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-home.devilop.me/home/07/07_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-home.devilop.me/home/07/07_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-home.devilop.me/home/07/07_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-home.devilop.me/home/07/07_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-home.devilop.me/home/07/07_6.jpg',
    product_price: '0',
    category_id: 1
  },
  {
    product_id: "ECOKAPRODUCT08",
    product_name: "Rèm Lưới",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-home.devilop.me/home/08/08_1.png',
    product_thumbnail_two: 'https://ecoka-product-home.devilop.me/home/08/08_2.png',
    product_thumbnail_three: 'https://ecoka-product-home.devilop.me/home/08/08_3.png',
    product_thumbnail_four: 'https://ecoka-product-home.devilop.me/home/08/08_4.png',
    product_thumbnail_five: 'https://ecoka-product-home.devilop.me/home/08/08_5.png',
    product_thumbnail_six: 'https://ecoka-product-home.devilop.me/home/08/08_6.png',
    product_price: '0',
    category_id: 1
  },
  {
    product_id: "ECOKAPRODUCT09",
    product_name: "Giỏ Tre",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-kitchen.devilop.me/kitchen/09/09_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-kitchen.devilop.me/kitchen/09/09_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-kitchen.devilop.me/kitchen/09/09_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-kitchen.devilop.me/kitchen/09/09_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-kitchen.devilop.me/kitchen/09/09_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-kitchen.devilop.me/kitchen/09/09_6.jpg',
    product_price: '0',
    category_id: 2
  },
  {
    product_id: "ECOKAPRODUCT10",
    product_name: "Lót Ly Lục Bình",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-kitchen.devilop.me/kitchen/10/10_1.JPG',
    product_thumbnail_two: 'https://ecoka-product-kitchen.devilop.me/kitchen/10/10_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-kitchen.devilop.me/kitchen/10/10_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-kitchen.devilop.me/kitchen/10/10_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-kitchen.devilop.me/kitchen/10/10_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-kitchen.devilop.me/kitchen/10/10_6.jpg',
    product_price: '0',
    category_id: 2
  },
  {
    product_id: "ECOKAPRODUCT11",
    product_name: "Lót Ly Macrame",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-kitchen.devilop.me/kitchen/11/11_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-kitchen.devilop.me/kitchen/11/11_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-kitchen.devilop.me/kitchen/11/11_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-kitchen.devilop.me/kitchen/11/11_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-kitchen.devilop.me/kitchen/11/11_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-kitchen.devilop.me/kitchen/11/11_6.jpg',
    product_price: '0',
    category_id: 2
  },
  {
    product_id: "ECOKAPRODUCT12",
    product_name: "Giỏ Đựng Macrame 30cm-Beige",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-kitchen.devilop.me/kitchen/12/12_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-kitchen.devilop.me/kitchen/12/12_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-kitchen.devilop.me/kitchen/12/12_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-kitchen.devilop.me/kitchen/12/12_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-kitchen.devilop.me/kitchen/12/12_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-kitchen.devilop.me/kitchen/12/12_6.jpg',
    product_price: '0',
    category_id: 2
  },
  {
    product_id: "ECOKAPRODUCT13",
    product_name: "Giỏ Đựng Macrame 30cm-Socola",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-kitchen.devilop.me/kitchen/13/13_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-kitchen.devilop.me/kitchen/13/13_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-kitchen.devilop.me/kitchen/13/13_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-kitchen.devilop.me/kitchen/13/13_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-kitchen.devilop.me/kitchen/13/13_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-kitchen.devilop.me/kitchen/13/13_6.jpg',
    product_price: '0',
    category_id: 2
  },
  {
    product_id: "ECOKAPRODUCT14",
    product_name: "Giỏ Đựng Cỏ Biển Vuông 30cm",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-kitchen.devilop.me/kitchen/14/14_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-kitchen.devilop.me/kitchen/14/14_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-kitchen.devilop.me/kitchen/14/14_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-kitchen.devilop.me/kitchen/14/14_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-kitchen.devilop.me/kitchen/14/14_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-kitchen.devilop.me/kitchen/14/14_6.jpg',
    product_price: '0',
    category_id: 2
  },
  {
    product_id: "ECOKAPRODUCT15",
    product_name: "Giỏ Đựng Lục Bình Có Lỗ 3",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-kitchen.devilop.me/kitchen/15/15_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-kitchen.devilop.me/kitchen/15/15_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-kitchen.devilop.me/kitchen/15/15_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-kitchen.devilop.me/kitchen/15/15_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-kitchen.devilop.me/kitchen/15/15_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-kitchen.devilop.me/kitchen/15/15_6.jpg',
    product_price: '0',
    category_id: 2
  },
  {
    product_id: "ECOKAPRODUCT16",
    product_name: "Giỏ Đựng Lục Bình Xca Set 3",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-kitchen.devilop.me/kitchen/16/16_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-kitchen.devilop.me/kitchen/16/16_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-kitchen.devilop.me/kitchen/16/16_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-kitchen.devilop.me/kitchen/16/16_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-kitchen.devilop.me/kitchen/16/16_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-kitchen.devilop.me/kitchen/16/16_6.jpg',
    product_price: '0',
    category_id: 2
  },
  {
    product_id: "ECOKAPRODUCT17",
    product_name: "Bộ Lục Bình Trữ Nước 3-SF",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-kitchen.devilop.me/kitchen/17/17_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-kitchen.devilop.me/kitchen/17/17_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-kitchen.devilop.me/kitchen/17/17_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-kitchen.devilop.me/kitchen/17/17_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-kitchen.devilop.me/kitchen/17/17_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-kitchen.devilop.me/kitchen/17/17_6.jpg',
    product_price: '0',
    category_id: 2
  },
  {
    product_id: "ECOKAPRODUCT18",
    product_name: "Bình Lục Bình Vuông 30cm",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-kitchen.devilop.me/kitchen/18/18_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-kitchen.devilop.me/kitchen/18/18_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-kitchen.devilop.me/kitchen/18/18_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-kitchen.devilop.me/kitchen/18/18_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-kitchen.devilop.me/kitchen/18/18_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-kitchen.devilop.me/kitchen/18/18_6.jpg',
    product_price: '0',
    category_id: 2
  },
  {
    product_id: "ECOKAPRODUCT19",
    product_name: "Túi 3 Tinh - Vàng Hồng Đỏ",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-fashion.devilop.me/fashion/19/19_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-fashion.devilop.me/fashion/19/19_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-fashion.devilop.me/fashion/19/19_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-fashion.devilop.me/fashion/19/19_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-fashion.devilop.me/fashion/19/19_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-fashion.devilop.me/fashion/19/19_6.jpg',
    product_price: '0',
    category_id: 4
  },
  {
    product_id: "ECOKAPRODUCT20",
    product_name: "Túi 3 Màu - Vàng Nâu",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-fashion.devilop.me/fashion/20/20_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-fashion.devilop.me/fashion/20/20_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-fashion.devilop.me/fashion/20/20_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-fashion.devilop.me/fashion/20/20_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-fashion.devilop.me/fashion/20/20_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-fashion.devilop.me/fashion/20/20_6.jpg',
    product_price: '0',
    category_id: 4
  },
  {
    product_id: "ECOKAPRODUCT21",
    product_name: "Túi 3 Màu - Màu Trắng Nâu",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-fashion.devilop.me/fashion/21/21_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-fashion.devilop.me/fashion/21/21_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-fashion.devilop.me/fashion/21/21_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-fashion.devilop.me/fashion/21/21_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-fashion.devilop.me/fashion/21/21_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-fashion.devilop.me/fashion/21/21_6.jpg',
    product_price: '0',
    category_id: 4
  },
  {
    product_id: "ECOKAPRODUCT22",
    product_name: "Túi Cói Kem",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-fashion.devilop.me/fashion/22/22_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-fashion.devilop.me/fashion/22/22_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-fashion.devilop.me/fashion/22/22_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-fashion.devilop.me/fashion/22/22_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-fashion.devilop.me/fashion/22/22_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-fashion.devilop.me/fashion/22/22_6.jpg',
    product_price: '0',
    category_id: 4
  },
  {
    product_id: "ECOKAPRODUCT23",
    product_name: "Túi Cói MixColor",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-fashion.devilop.me/fashion/23/23_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-fashion.devilop.me/fashion/23/23_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-fashion.devilop.me/fashion/23/23_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-fashion.devilop.me/fashion/23/23_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-fashion.devilop.me/fashion/23/23_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-fashion.devilop.me/fashion/23/23_6.jpg',
    product_price: '0',
    category_id: 4
  },
  {
    product_id: "ECOKAPRODUCT24",
    product_name: "Túc Lục Bình",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-fashion.devilop.me/fashion/24/24_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-fashion.devilop.me/fashion/24/24_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-fashion.devilop.me/fashion/24/24_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-fashion.devilop.me/fashion/24/24_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-fashion.devilop.me/fashion/24/24_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-fashion.devilop.me/fashion/24/24_6.jpg',
    product_price: '0',
    category_id: 4
  },
  {
    product_id: "ECOKAPRODUCT25",
    product_name: "Túi Lục Bình Chim Công",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-fashion.devilop.me/fashion/25/25_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-fashion.devilop.me/fashion/25/25_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-fashion.devilop.me/fashion/25/25_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-fashion.devilop.me/fashion/25/25_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-fashion.devilop.me/fashion/25/25_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-fashion.devilop.me/fashion/25/25_6.jpg',
    product_price: '0',
    category_id: 4
  },
  {
    product_id: "ECOKAPRODUCT26",
    product_name: "Túi Lục Bình Hoa Độc",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-fashion.devilop.me/fashion/26/26_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-fashion.devilop.me/fashion/26/26_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-fashion.devilop.me/fashion/26/26_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-fashion.devilop.me/fashion/26/26_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-fashion.devilop.me/fashion/26/26_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-fashion.devilop.me/fashion/26/26_6.jpg',
    product_price: '0',
    category_id: 4
  },
  {
    product_id: "ECOKAPRODUCT27",
    product_name: "Túi Lục Bình Hoa Miếng",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-fashion.devilop.me/fashion/27/27_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-fashion.devilop.me/fashion/27/27_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-fashion.devilop.me/fashion/27/27_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-fashion.devilop.me/fashion/27/27_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-fashion.devilop.me/fashion/27/27_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-fashion.devilop.me/fashion/27/27_6.jpg',
    product_price: '0',
    category_id: 4
  },
  {
    product_id: "ECOKAPRODUCT28",
    product_name: "Túi Lục Bình Quay Đá 26",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-fashion.devilop.me/fashion/28/28_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-fashion.devilop.me/fashion/28/28_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-fashion.devilop.me/fashion/28/28_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-fashion.devilop.me/fashion/28/28_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-fashion.devilop.me/fashion/28/28_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-fashion.devilop.me/fashion/28/28_6.jpg',
    product_price: '0',
    category_id: 4
  },
  {
    product_id: "ECOKAPRODUCT29",
    product_name: "Túi Lục Bình Quay Đà",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-fashion.devilop.me/fashion/29/29_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-fashion.devilop.me/fashion/29/29_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-fashion.devilop.me/fashion/29/29_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-fashion.devilop.me/fashion/29/29_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-fashion.devilop.me/fashion/29/29_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-fashion.devilop.me/fashion/29/29_6.jpg',
    product_price: '0',
    category_id: 4
  },
  {
    product_id: "ECOKAPRODUCT30",
    product_name: "Túi Lục Bình Quay Da Macrame",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-fashion.devilop.me/fashion/30/30_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-fashion.devilop.me/fashion/30/30_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-fashion.devilop.me/fashion/30/30_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-fashion.devilop.me/fashion/30/30_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-fashion.devilop.me/fashion/30/30_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-fashion.devilop.me/fashion/30/30_6.jpg',
    product_price: '0',
    category_id: 4
  },
  {
    product_id: "ECOKAPRODUCT31",
    product_name: "Túi Macrame Điện Thoại - Hồng",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-fashion.devilop.me/fashion/31/31_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-fashion.devilop.me/fashion/31/31_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-fashion.devilop.me/fashion/31/31_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-fashion.devilop.me/fashion/31/31_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-fashion.devilop.me/fashion/31/31_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-fashion.devilop.me/fashion/31/31_6.jpg',
    product_price: '0',
    category_id: 4
  },
  {
    product_id: "ECOKAPRODUCT32",
    product_name: "Túi Macrame Điện Thoại - Kem",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-fashion.devilop.me/fashion/32/32_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-fashion.devilop.me/fashion/32/32_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-fashion.devilop.me/fashion/32/32_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-fashion.devilop.me/fashion/32/32_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-fashion.devilop.me/fashion/32/32_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-fashion.devilop.me/fashion/32/32_6.jpg',
    product_price: '0',
    category_id: 4
  },
  {
    product_id: "ECOKAPRODUCT33",
    product_name: "Túi Macrame Laptop 32",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-fashion.devilop.me/fashion/33/33_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-fashion.devilop.me/fashion/33/33_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-fashion.devilop.me/fashion/33/33_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-fashion.devilop.me/fashion/33/33_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-fashion.devilop.me/fashion/33/33_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-fashion.devilop.me/fashion/33/33_6.jpg',
    product_price: '0',
    category_id: 4
  },
  {
    product_id: "ECOKAPRODUCT34",
    product_name: "Túi Macrame Ngang - Kem",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/34/34_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/34/34_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/34/34_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/34/34_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/34/34_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/34/34_6.jpg',
    product_price: '0',
    category_id: 4
  },
  {
    product_id: "ECOKAPRODUCT35",
    product_name: "Túi Trống - Kem Nâu",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/35/35_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/35/35_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/35/35_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/35/35_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/35/35_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/35/35_6.jpg',
    product_price: '0',
    category_id: 4
  },
  {
    product_id: "ECOKAPRODUCT36",
    product_name: "Túi Trống - Kem Vàng",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/36/36_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/36/36_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/36/36_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/36/36_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/36/36_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/36/36_6.jpg',
    product_price: '0',
    category_id: 4
  },
  {
    product_id: "ECOKAPRODUCT37",
    product_name: "Mũ Đi Biển Hoa Lục Bình Cho Nữ Sang Trọng",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/37/37_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/37/37_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/37/37_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/37/37_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/37/37_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/37/37_6.jpg',
    product_price: '0',
    category_id: 4
  },
  {
    product_id: "ECOKAPRODUCT38",
    product_name: "Mũ Đi Biển Lục Bình Dây Đơn Cho Nữ",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/38/38_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/38/38_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/38/38_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/38/38_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/38/38_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/38/38_6.jpg',
    product_price: '0',
    category_id: 4
  },
  // ======================================
  {
    product_id: "ECOKAPRODUCT39",
    product_name: "Giá Giày",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-v2.devilop.me/home/gia-giay/gia-giay_1.jpg',
    product_thumbnail_two: 'https://ecoka-v2.devilop.me/home/gia-giay/gia-giay_2.jpg',
    product_thumbnail_three: '',
    product_thumbnail_four: '',
    product_thumbnail_five: '',
    product_thumbnail_six: '',
    product_price: '0',
    category_id: 1
  },
  {
    product_id: "ECOKAPRODUCT40",
    product_name: "Sọt Đựng",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-v2.devilop.me/home/storage-01/storage-01_1.jpg',
    product_thumbnail_two: 'https://ecoka-v2.devilop.me/home/storage-01/storage-01_2.jpg',
    product_thumbnail_three: 'https://ecoka-v2.devilop.me/home/storage-01/storage-01_3.jpg',
    product_thumbnail_four: 'https://ecoka-v2.devilop.me/home/storage-01/storage-01_4.jpg',
    product_thumbnail_five: 'https://ecoka-v2.devilop.me/home/storage-01/storage-01_5.jpg',
    product_thumbnail_six: '',
    product_price: '0',
    category_id: 1
  },
  {
    product_id: "ECOKAPRODUCT41",
    product_name: "Sọt Đựng",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-v2.devilop.me/home/storage-02/storage-02_1.jpg',
    product_thumbnail_two: 'https://ecoka-v2.devilop.me/home/storage-02/storage-02_2.jpg',
    product_thumbnail_three: 'https://ecoka-v2.devilop.me/home/storage-02/storage-02_3.jpg',
    product_thumbnail_four: 'https://ecoka-v2.devilop.me/home/storage-02/storage-02_4.jpg',
    product_thumbnail_five: 'https://ecoka-v2.devilop.me/home/storage-02/storage-02_5.jpg',
    product_thumbnail_six: '',
    product_price: '0',
    category_id: 1
  },
  {
    product_id: "ECOKAPRODUCT42",
    product_name: "Sọt Đựng",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-v2.devilop.me/home/storage-03/storage-03_1.jpg',
    product_thumbnail_two: 'https://ecoka-v2.devilop.me/home/storage-03/storage-03_2.jpg',
    product_thumbnail_three: 'https://ecoka-v2.devilop.me/home/storage-03/storage-03_3.jpg',
    product_thumbnail_four: 'https://ecoka-v2.devilop.me/home/storage-03/storage-03_4.jpg',
    product_thumbnail_five: 'https://ecoka-v2.devilop.me/home/storage-03/storage-03_5.jpg',
    product_thumbnail_six: 'https://ecoka-v2.devilop.me/home/storage-03/storage-03_6.jpg',
    product_price: '0',
    category_id: 1
  },
  // ======================================
  {
    product_id: "ECOKAPRODUCT43",
    product_name: "Coster",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-v2.devilop.me/kitchen/coster/coster_1.jpg',
    product_thumbnail_two: 'https://ecoka-v2.devilop.me/kitchen/coster/coster_2.jpg',
    product_thumbnail_three: 'https://ecoka-v2.devilop.me/kitchen/coster/coster_3.jpg',
    product_thumbnail_four: 'https://ecoka-v2.devilop.me/kitchen/coster/coster_4.jpg',
    product_thumbnail_five: 'https://ecoka-v2.devilop.me/kitchen/coster/coster_5.jpg',
    product_thumbnail_six: 'https://ecoka-v2.devilop.me/kitchen/coster/coster_6.jpg',
    product_price: '0',
    category_id: 2
  },
  {
    product_id: "ECOKAPRODUCT44",
    product_name: "Holder",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-v2.devilop.me/kitchen/holder/holder.jpg',
    product_thumbnail_two: '',
    product_thumbnail_three: '',
    product_thumbnail_four: '',
    product_thumbnail_five: '',
    product_thumbnail_six: '',
    product_price: '0',
    category_id: 2
  },
  {
    product_id: "ECOKAPRODUCT45",
    product_name: "Napkin Ring",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-v2.devilop.me/kitchen/napkin-ring/napkin-ring_1.jpg',
    product_thumbnail_two: 'https://ecoka-v2.devilop.me/kitchen/napkin-ring/napkin-ring_2.jpg',
    product_thumbnail_three: 'https://ecoka-v2.devilop.me/kitchen/napkin-ring/napkin-ring_3.jpg',
    product_thumbnail_four: 'https://ecoka-v2.devilop.me/kitchen/napkin-ring/napkin-ring_4.jpg',
    product_thumbnail_five: 'https://ecoka-v2.devilop.me/kitchen/napkin-ring/napkin-ring_5.jpg',
    product_thumbnail_six: 'https://ecoka-v2.devilop.me/kitchen/napkin-ring/napkin-ring_6.jpg',
    product_price: '0',
    category_id: 2
  },
  {
    product_id: "ECOKAPRODUCT46",
    product_name: "Placemat",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-v2.devilop.me/kitchen/placemat-01/placemat-01_1.jpg',
    product_thumbnail_two: 'https://ecoka-v2.devilop.me/kitchen/placemat-01/placemat-01_2.jpg',
    product_thumbnail_three: 'https://ecoka-v2.devilop.me/kitchen/placemat-01/placemat-01_3jpg',
    product_thumbnail_four: 'https://ecoka-v2.devilop.me/kitchen/placemat-01/placemat-01_4.jpg',
    product_thumbnail_five: 'https://ecoka-v2.devilop.me/kitchen/placemat-01/placemat-01_5.jpg',
    product_thumbnail_six: 'https://ecoka-v2.devilop.me/kitchen/placemat-01/placemat-01_6.jpg',
    product_price: '0',
    category_id: 2
  },
  {
    product_id: "ECOKAPRODUCT47",
    product_name: "Placemat",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-v2.devilop.me/kitchen/placemat-02/placemat-02_1.jpg',
    product_thumbnail_two: 'https://ecoka-v2.devilop.me/kitchen/placemat-02/placemat-02_2.jpg',
    product_thumbnail_three: 'https://ecoka-v2.devilop.me/kitchen/placemat-02/placemat-02_3jpg',
    product_thumbnail_four: 'https://ecoka-v2.devilop.me/kitchen/placemat-02/placemat-02_4.jpg',
    product_thumbnail_five: 'https://ecoka-v2.devilop.me/kitchen/placemat-02/placemat-02_5.jpg',
    product_thumbnail_six: 'https://ecoka-v2.devilop.me/kitchen/placemat-02/placemat-02_6.jpg',
    product_price: '0',
    category_id: 2
  },
  {
    product_id: "ECOKAPRODUCT48",
    product_name: "Placemat",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-v2.devilop.me/kitchen/placemat-03/placemat-03_1.jpg',
    product_thumbnail_two: 'https://ecoka-v2.devilop.me/kitchen/placemat-03/placemat-03_2.jpg',
    product_thumbnail_three: 'https://ecoka-v2.devilop.me/kitchen/placemat-03/placemat-03_3jpg',
    product_thumbnail_four: 'https://ecoka-v2.devilop.me/kitchen/placemat-03/placemat-03_4.jpg',
    product_thumbnail_five: 'https://ecoka-v2.devilop.me/kitchen/placemat-03/placemat-03_5.jpg',
    product_thumbnail_six: '',
    product_price: '0',
    category_id: 2
  },
  // ======================================
  {
    product_id: "ECOKAPRODUCT49",
    product_name: "Benches",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-v2.devilop.me/furniture/benches/benches.jpg',
    product_thumbnail_two: '',
    product_thumbnail_three: '',
    product_thumbnail_four: '',
    product_thumbnail_five: '',
    product_thumbnail_six: '',
    product_price: '0',
    category_id: 3
  },
  {
    product_id: "ECOKAPRODUCT50",
    product_name: "Bộ Sofa",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-v2.devilop.me/furniture/bo-sofa/bo-sofa.jpg',
    product_thumbnail_two: '',
    product_thumbnail_three: '',
    product_thumbnail_four: '',
    product_thumbnail_five: '',
    product_thumbnail_six: '',
    product_price: '0',
    category_id: 3
  },
  {
    product_id: "ECOKAPRODUCT51",
    product_name: "Chair",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-v2.devilop.me/furniture/chair/chair.jpg',
    product_thumbnail_two: '',
    product_thumbnail_three: '',
    product_thumbnail_four: '',
    product_thumbnail_five: '',
    product_thumbnail_six: '',
    product_price: '0',
    category_id: 3
  },
  {
    product_id: "ECOKAPRODUCT52",
    product_name: "Coffee Table",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-v2.devilop.me/furniture/coffee-table/coffee-table.jpg',
    product_thumbnail_two: '',
    product_thumbnail_three: '',
    product_thumbnail_four: '',
    product_thumbnail_five: '',
    product_thumbnail_six: '',
    product_price: '0',
    category_id: 3
  },
  {
    product_id: "ECOKAPRODUCT53",
    product_name: "Đôn",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-v2.devilop.me/furniture/don/don_1.jpg',
    product_thumbnail_two: 'https://ecoka-v2.devilop.me/furniture/don/don_2.jpg',
    product_thumbnail_three: '',
    product_thumbnail_four: '',
    product_thumbnail_five: '',
    product_thumbnail_six: '',
    product_price: '0',
    category_id: 3
  },
  {
    product_id: "ECOKAPRODUCT54",
    product_name: "Home Storage",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-v2.devilop.me/furniture/home-storage/home-storage_1.jpg',
    product_thumbnail_two: 'https://ecoka-v2.devilop.me/furniture/home-storage/home-storage_2.jpg',
    product_thumbnail_three: 'https://ecoka-v2.devilop.me/furniture/home-storage/home-storage_3.jpg',
    product_thumbnail_four: '',
    product_thumbnail_five: '',
    product_thumbnail_six: '',
    product_price: '0',
    category_id: 3
  },
  {
    product_id: "ECOKAPRODUCT55",
    product_name: "Sofa",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-v2.devilop.me/furniture/sofa/sofa.jpg',
    product_thumbnail_two: '',
    product_thumbnail_three: '',
    product_thumbnail_four: '',
    product_thumbnail_five: '',
    product_thumbnail_six: '',
    product_price: '0',
    category_id: 3
  },
  {
    product_id: "ECOKAPRODUCT56",
    product_name: "Sofa Table",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-v2.devilop.me/furniture/sofa-table/sofa-table_1.jpg',
    product_thumbnail_two: 'https://ecoka-v2.devilop.me/furniture/sofa-table/sofa-table_2.jpg',
    product_thumbnail_three: 'https://ecoka-v2.devilop.me/furniture/sofa-table/sofa-table_3.jpg',
    product_thumbnail_four: 'https://ecoka-v2.devilop.me/furniture/sofa-table/sofa-table_4.jpg',
    product_thumbnail_five: 'https://ecoka-v2.devilop.me/furniture/sofa-table/sofa-table_5.jpg',
    product_thumbnail_six: 'https://ecoka-v2.devilop.me/furniture/sofa-table/sofa-table_6.jpg',
    product_price: '0',
    category_id: 3
  },
  {
    product_id: "ECOKAPRODUCT57",
    product_name: "Sofa Table Restangle",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-v2.devilop.me/furniture/sofa-table-restangle/sofa-table-restangle.jpg',
    product_thumbnail_two: '',
    product_thumbnail_three: '',
    product_thumbnail_four: '',
    product_thumbnail_five: '',
    product_thumbnail_six: '',
    product_price: '0',
    category_id: 3
  },
  {
    product_id: "ECOKAPRODUCT58",
    product_name: "Tủ Kệ",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-v2.devilop.me/furniture/tu-ke/tu-ke_1.jpg',
    product_thumbnail_two: 'https://ecoka-v2.devilop.me/furniture/tu-ke/tu-ke_2.jpg',
    product_thumbnail_three: 'https://ecoka-v2.devilop.me/furniture/tu-ke/tu-ke_3.jpg',
    product_thumbnail_four: 'https://ecoka-v2.devilop.me/furniture/tu-ke/tu-ke_4.jpg',
    product_thumbnail_five: '',
    product_thumbnail_six: '',
    product_price: '0',
    category_id: 3
  },
];

const PRODUCTS_EN = [
  {
    product_id: "ECOKAPRODUCT01",
    product_name: "Nhẫn Lục Bình",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-home.devilop.me/home/01/01_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-home.devilop.me/home/01/01_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-home.devilop.me/home/01/01_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-home.devilop.me/home/01/01_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-home.devilop.me/home/01/01_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-home.devilop.me/home/01/01_6.jpg',
    product_price: '0',
    category_id: 2
  },
  {
    product_id: "ECOKAPRODUCT02",
    product_name: "Thảm Cỏ Biển Hoa 4ft",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-home.devilop.me/home/02/02_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-home.devilop.me/home/02/02_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-home.devilop.me/home/02/02_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-home.devilop.me/home/02/02_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-home.devilop.me/home/02/02_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-home.devilop.me/home/02/02_6.jpg',
    product_price: '0',
    category_id: 1
  },
  {
    product_id: "ECOKAPRODUCT03",
    product_name: "Thảm Cỏ Biển 3ft",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-home.devilop.me/home/03/03_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-home.devilop.me/home/03/03_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-home.devilop.me/home/03/03_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-home.devilop.me/home/03/03_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-home.devilop.me/home/03/03_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-home.devilop.me/home/03/03_6.jpg',
    product_price: '0',
    category_id: 1
  },
  {
    product_id: "ECOKAPRODUCT04",
    product_name: "Rèm Macrame-Màu Be",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-home.devilop.me/home/04/04_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-home.devilop.me/home/04/04_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-home.devilop.me/home/04/04_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-home.devilop.me/home/04/04_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-home.devilop.me/home/04/04_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-home.devilop.me/home/04/04_6.jpg',
    product_price: '0',
    category_id: 1
  },
  {
    product_id: "ECOKAPRODUCT05",
    product_name: "Rèm Macrame-Vàng",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-home.devilop.me/home/05/05_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-home.devilop.me/home/05/05_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-home.devilop.me/home/05/05_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-home.devilop.me/home/05/05_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-home.devilop.me/home/05/05_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-home.devilop.me/home/05/05_6.jpg',
    product_price: '0',
    category_id: 1
  },
  {
    product_id: "ECOKAPRODUCT06",
    product_name: "Rèm Macrame-Xám",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-home.devilop.me/home/06/06_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-home.devilop.me/home/06/06_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-home.devilop.me/home/06/06_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-home.devilop.me/home/06/06_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-home.devilop.me/home/06/06_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-home.devilop.me/home/06/06_6.jpg',
    product_price: '0',
    category_id: 1
  },
  {
    product_id: "ECOKAPRODUCT07",
    product_name: "Rèm Macrarme-Nâu Hồng",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-home.devilop.me/home/07/07_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-home.devilop.me/home/07/07_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-home.devilop.me/home/07/07_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-home.devilop.me/home/07/07_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-home.devilop.me/home/07/07_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-home.devilop.me/home/07/07_6.jpg',
    product_price: '0',
    category_id: 1
  },
  {
    product_id: "ECOKAPRODUCT08",
    product_name: "Rèm Lưới",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-home.devilop.me/home/08/08_1.png',
    product_thumbnail_two: 'https://ecoka-product-home.devilop.me/home/08/08_2.png',
    product_thumbnail_three: 'https://ecoka-product-home.devilop.me/home/08/08_3.png',
    product_thumbnail_four: 'https://ecoka-product-home.devilop.me/home/08/08_4.png',
    product_thumbnail_five: 'https://ecoka-product-home.devilop.me/home/08/08_5.png',
    product_thumbnail_six: 'https://ecoka-product-home.devilop.me/home/08/08_6.png',
    product_price: '0',
    category_id: 1
  },
  {
    product_id: "ECOKAPRODUCT09",
    product_name: "Giỏ Tre",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-kitchen.devilop.me/kitchen/09/09_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-kitchen.devilop.me/kitchen/09/09_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-kitchen.devilop.me/kitchen/09/09_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-kitchen.devilop.me/kitchen/09/09_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-kitchen.devilop.me/kitchen/09/09_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-kitchen.devilop.me/kitchen/09/09_6.jpg',
    product_price: '0',
    category_id: 2
  },
  {
    product_id: "ECOKAPRODUCT10",
    product_name: "Lót Ly Lục Bình",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-kitchen.devilop.me/kitchen/10/10_1.JPG',
    product_thumbnail_two: 'https://ecoka-product-kitchen.devilop.me/kitchen/10/10_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-kitchen.devilop.me/kitchen/10/10_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-kitchen.devilop.me/kitchen/10/10_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-kitchen.devilop.me/kitchen/10/10_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-kitchen.devilop.me/kitchen/10/10_6.jpg',
    product_price: '0',
    category_id: 2
  },
  {
    product_id: "ECOKAPRODUCT11",
    product_name: "Lót Ly Macrame",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-kitchen.devilop.me/kitchen/11/11_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-kitchen.devilop.me/kitchen/11/11_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-kitchen.devilop.me/kitchen/11/11_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-kitchen.devilop.me/kitchen/11/11_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-kitchen.devilop.me/kitchen/11/11_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-kitchen.devilop.me/kitchen/11/11_6.jpg',
    product_price: '0',
    category_id: 2
  },
  {
    product_id: "ECOKAPRODUCT12",
    product_name: "Giỏ Đựng Macrame 30cm-Beige",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-kitchen.devilop.me/kitchen/12/12_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-kitchen.devilop.me/kitchen/12/12_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-kitchen.devilop.me/kitchen/12/12_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-kitchen.devilop.me/kitchen/12/12_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-kitchen.devilop.me/kitchen/12/12_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-kitchen.devilop.me/kitchen/12/12_6.jpg',
    product_price: '0',
    category_id: 2
  },
  {
    product_id: "ECOKAPRODUCT13",
    product_name: "Giỏ Đựng Macrame 30cm-Socola",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-kitchen.devilop.me/kitchen/13/13_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-kitchen.devilop.me/kitchen/13/13_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-kitchen.devilop.me/kitchen/13/13_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-kitchen.devilop.me/kitchen/13/13_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-kitchen.devilop.me/kitchen/13/13_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-kitchen.devilop.me/kitchen/13/13_6.jpg',
    product_price: '0',
    category_id: 2
  },
  {
    product_id: "ECOKAPRODUCT14",
    product_name: "Giỏ Đựng Cỏ Biển Vuông 30cm",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-kitchen.devilop.me/kitchen/14/14_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-kitchen.devilop.me/kitchen/14/14_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-kitchen.devilop.me/kitchen/14/14_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-kitchen.devilop.me/kitchen/14/14_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-kitchen.devilop.me/kitchen/14/14_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-kitchen.devilop.me/kitchen/14/14_6.jpg',
    product_price: '0',
    category_id: 2
  },
  {
    product_id: "ECOKAPRODUCT15",
    product_name: "Giỏ Đựng Lục Bình Có Lỗ 3",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-kitchen.devilop.me/kitchen/15/15_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-kitchen.devilop.me/kitchen/15/15_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-kitchen.devilop.me/kitchen/15/15_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-kitchen.devilop.me/kitchen/15/15_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-kitchen.devilop.me/kitchen/15/15_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-kitchen.devilop.me/kitchen/15/15_6.jpg',
    product_price: '0',
    category_id: 2
  },
  {
    product_id: "ECOKAPRODUCT16",
    product_name: "Giỏ Đựng Lục Bình Xca Set 3",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-kitchen.devilop.me/kitchen/16/16_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-kitchen.devilop.me/kitchen/16/16_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-kitchen.devilop.me/kitchen/16/16_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-kitchen.devilop.me/kitchen/16/16_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-kitchen.devilop.me/kitchen/16/16_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-kitchen.devilop.me/kitchen/16/16_6.jpg',
    product_price: '0',
    category_id: 2
  },
  {
    product_id: "ECOKAPRODUCT17",
    product_name: "Bộ Lục Bình Trữ Nước 3-SF",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-kitchen.devilop.me/kitchen/17/17_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-kitchen.devilop.me/kitchen/17/17_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-kitchen.devilop.me/kitchen/17/17_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-kitchen.devilop.me/kitchen/17/17_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-kitchen.devilop.me/kitchen/17/17_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-kitchen.devilop.me/kitchen/17/17_6.jpg',
    product_price: '0',
    category_id: 2
  },
  {
    product_id: "ECOKAPRODUCT18",
    product_name: "Bình Lục Bình Vuông 30cm",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-kitchen.devilop.me/kitchen/18/18_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-kitchen.devilop.me/kitchen/18/18_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-kitchen.devilop.me/kitchen/18/18_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-kitchen.devilop.me/kitchen/18/18_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-kitchen.devilop.me/kitchen/18/18_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-kitchen.devilop.me/kitchen/18/18_6.jpg',
    product_price: '0',
    category_id: 2
  },
  {
    product_id: "ECOKAPRODUCT19",
    product_name: "Túi 3 Tinh - Vàng Hồng Đỏ",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-fashion.devilop.me/fashion/19/19_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-fashion.devilop.me/fashion/19/19_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-fashion.devilop.me/fashion/19/19_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-fashion.devilop.me/fashion/19/19_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-fashion.devilop.me/fashion/19/19_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-fashion.devilop.me/fashion/19/19_6.jpg',
    product_price: '0',
    category_id: 4
  },
  {
    product_id: "ECOKAPRODUCT20",
    product_name: "Túi 3 Màu - Vàng Nâu",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-fashion.devilop.me/fashion/20/20_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-fashion.devilop.me/fashion/20/20_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-fashion.devilop.me/fashion/20/20_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-fashion.devilop.me/fashion/20/20_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-fashion.devilop.me/fashion/20/20_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-fashion.devilop.me/fashion/20/20_6.jpg',
    product_price: '0',
    category_id: 4
  },
  {
    product_id: "ECOKAPRODUCT21",
    product_name: "Túi 3 Màu - Màu Trắng Nâu",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-fashion.devilop.me/fashion/21/21_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-fashion.devilop.me/fashion/21/21_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-fashion.devilop.me/fashion/21/21_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-fashion.devilop.me/fashion/21/21_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-fashion.devilop.me/fashion/21/21_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-fashion.devilop.me/fashion/21/21_6.jpg',
    product_price: '0',
    category_id: 4
  },
  {
    product_id: "ECOKAPRODUCT22",
    product_name: "Túi Cói Kem",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-fashion.devilop.me/fashion/22/22_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-fashion.devilop.me/fashion/22/22_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-fashion.devilop.me/fashion/22/22_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-fashion.devilop.me/fashion/22/22_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-fashion.devilop.me/fashion/22/22_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-fashion.devilop.me/fashion/22/22_6.jpg',
    product_price: '0',
    category_id: 4
  },
  {
    product_id: "ECOKAPRODUCT23",
    product_name: "Túi Cói MixColor",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-fashion.devilop.me/fashion/23/23_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-fashion.devilop.me/fashion/23/23_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-fashion.devilop.me/fashion/23/23_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-fashion.devilop.me/fashion/23/23_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-fashion.devilop.me/fashion/23/23_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-fashion.devilop.me/fashion/23/23_6.jpg',
    product_price: '0',
    category_id: 4
  },
  {
    product_id: "ECOKAPRODUCT24",
    product_name: "Túc Lục Bình",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-fashion.devilop.me/fashion/24/24_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-fashion.devilop.me/fashion/24/24_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-fashion.devilop.me/fashion/24/24_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-fashion.devilop.me/fashion/24/24_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-fashion.devilop.me/fashion/24/24_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-fashion.devilop.me/fashion/24/24_6.jpg',
    product_price: '0',
    category_id: 4
  },
  {
    product_id: "ECOKAPRODUCT25",
    product_name: "Túi Lục Bình Chim Công",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-fashion.devilop.me/fashion/25/25_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-fashion.devilop.me/fashion/25/25_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-fashion.devilop.me/fashion/25/25_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-fashion.devilop.me/fashion/25/25_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-fashion.devilop.me/fashion/25/25_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-fashion.devilop.me/fashion/25/25_6.jpg',
    product_price: '0',
    category_id: 4
  },
  {
    product_id: "ECOKAPRODUCT26",
    product_name: "Túi Lục Bình Hoa Độc",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-fashion.devilop.me/fashion/26/26_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-fashion.devilop.me/fashion/26/26_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-fashion.devilop.me/fashion/26/26_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-fashion.devilop.me/fashion/26/26_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-fashion.devilop.me/fashion/26/26_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-fashion.devilop.me/fashion/26/26_6.jpg',
    product_price: '0',
    category_id: 4
  },
  {
    product_id: "ECOKAPRODUCT27",
    product_name: "Túi Lục Bình Hoa Miếng",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-fashion.devilop.me/fashion/27/27_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-fashion.devilop.me/fashion/27/27_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-fashion.devilop.me/fashion/27/27_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-fashion.devilop.me/fashion/27/27_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-fashion.devilop.me/fashion/27/27_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-fashion.devilop.me/fashion/27/27_6.jpg',
    product_price: '0',
    category_id: 4
  },
  {
    product_id: "ECOKAPRODUCT28",
    product_name: "Túi Lục Bình Quay Đá 26",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-fashion.devilop.me/fashion/28/28_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-fashion.devilop.me/fashion/28/28_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-fashion.devilop.me/fashion/28/28_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-fashion.devilop.me/fashion/28/28_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-fashion.devilop.me/fashion/28/28_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-fashion.devilop.me/fashion/28/28_6.jpg',
    product_price: '0',
    category_id: 4
  },
  {
    product_id: "ECOKAPRODUCT29",
    product_name: "Túi Lục Bình Quay Đà",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-fashion.devilop.me/fashion/29/29_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-fashion.devilop.me/fashion/29/29_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-fashion.devilop.me/fashion/29/29_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-fashion.devilop.me/fashion/29/29_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-fashion.devilop.me/fashion/29/29_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-fashion.devilop.me/fashion/29/29_6.jpg',
    product_price: '0',
    category_id: 4
  },
  {
    product_id: "ECOKAPRODUCT30",
    product_name: "Túi Lục Bình Quay Da Macrame",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-fashion.devilop.me/fashion/30/30_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-fashion.devilop.me/fashion/30/30_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-fashion.devilop.me/fashion/30/30_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-fashion.devilop.me/fashion/30/30_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-fashion.devilop.me/fashion/30/30_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-fashion.devilop.me/fashion/30/30_6.jpg',
    product_price: '0',
    category_id: 4
  },
  {
    product_id: "ECOKAPRODUCT31",
    product_name: "Túi Macrame Điện Thoại - Hồng",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-fashion.devilop.me/fashion/31/31_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-fashion.devilop.me/fashion/31/31_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-fashion.devilop.me/fashion/31/31_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-fashion.devilop.me/fashion/31/31_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-fashion.devilop.me/fashion/31/31_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-fashion.devilop.me/fashion/31/31_6.jpg',
    product_price: '0',
    category_id: 4
  },
  {
    product_id: "ECOKAPRODUCT32",
    product_name: "Túi Macrame Điện Thoại - Kem",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-fashion.devilop.me/fashion/32/32_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-fashion.devilop.me/fashion/32/32_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-fashion.devilop.me/fashion/32/32_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-fashion.devilop.me/fashion/32/32_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-fashion.devilop.me/fashion/32/32_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-fashion.devilop.me/fashion/32/32_6.jpg',
    product_price: '0',
    category_id: 4
  },
  {
    product_id: "ECOKAPRODUCT33",
    product_name: "Laptop 32 Túi Macrame",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-fashion.devilop.me/fashion/33/33_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-fashion.devilop.me/fashion/33/33_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-fashion.devilop.me/fashion/33/33_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-fashion.devilop.me/fashion/33/33_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-fashion.devilop.me/fashion/33/33_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-fashion.devilop.me/fashion/33/33_6.jpg',
    product_price: '0',
    category_id: 4
  },
  {
    product_id: "ECOKAPRODUCT34",
    product_name: "Túi Macrame Ngang - Kem",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/34/34_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/34/34_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/34/34_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/34/34_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/34/34_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/34/34_6.jpg',
    product_price: '0',
    category_id: 4
  },
  {
    product_id: "ECOKAPRODUCT35",
    product_name: "Túi Trống - Kem Nâu",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/35/35_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/35/35_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/35/35_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/35/35_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/35/35_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/35/35_6.jpg',
    product_price: '0',
    category_id: 4
  },
  {
    product_id: "ECOKAPRODUCT36",
    product_name: "Túi Trống - Kem Vàng",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/36/36_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/36/36_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/36/36_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/36/36_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/36/36_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/36/36_6.jpg',
    product_price: '0',
    category_id: 4
  },
  {
    product_id: "ECOKAPRODUCT37",
    product_name: "Mũ Đi Biển Hoa Lục Bình Cho Nữ Sang Trọng",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/37/37_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/37/37_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/37/37_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/37/37_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/37/37_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/37/37_6.jpg',
    product_price: '0',
    category_id: 4
  },
  {
    product_id: "ECOKAPRODUCT38",
    product_name: "Mũ Đi Biển Lục Bình Dây Đơn Cho Nữ",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/38/38_1.jpg',
    product_thumbnail_two: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/38/38_2.jpg',
    product_thumbnail_three: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/38/38_3.jpg',
    product_thumbnail_four: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/38/38_4.jpg',
    product_thumbnail_five: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/38/38_5.jpg',
    product_thumbnail_six: 'https://ecoka-product-fashion-02.devilop.me/fashion-02/38/38_6.jpg',
    product_price: '0',
    category_id: 4
  },
  // ======================================
  {
    product_id: "ECOKAPRODUCT39",
    product_name: "Giá Giày",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-v2.devilop.me/home/gia-giay/gia-giay_1.jpg',
    product_thumbnail_two: 'https://ecoka-v2.devilop.me/home/gia-giay/gia-giay_2.jpg',
    product_thumbnail_three: '',
    product_thumbnail_four: '',
    product_thumbnail_five: '',
    product_thumbnail_six: '',
    product_price: '0',
    category_id: 1
  },
  {
    product_id: "ECOKAPRODUCT40",
    product_name: "Storage",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-v2.devilop.me/home/storage-01/storage-01_1.jpg',
    product_thumbnail_two: 'https://ecoka-v2.devilop.me/home/storage-01/storage-01_2.jpg',
    product_thumbnail_three: 'https://ecoka-v2.devilop.me/home/storage-01/storage-01_3.jpg',
    product_thumbnail_four: 'https://ecoka-v2.devilop.me/home/storage-01/storage-01_4.jpg',
    product_thumbnail_five: 'https://ecoka-v2.devilop.me/home/storage-01/storage-01_5.jpg',
    product_thumbnail_six: '',
    product_price: '0',
    category_id: 1
  },
  {
    product_id: "ECOKAPRODUCT41",
    product_name: "Storage",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-v2.devilop.me/home/storage-02/storage-02_1.jpg',
    product_thumbnail_two: 'https://ecoka-v2.devilop.me/home/storage-02/storage-02_2.jpg',
    product_thumbnail_three: 'https://ecoka-v2.devilop.me/home/storage-02/storage-02_3.jpg',
    product_thumbnail_four: 'https://ecoka-v2.devilop.me/home/storage-02/storage-02_4.jpg',
    product_thumbnail_five: 'https://ecoka-v2.devilop.me/home/storage-02/storage-02_5.jpg',
    product_thumbnail_six: '',
    product_price: '0',
    category_id: 1
  },
  {
    product_id: "ECOKAPRODUCT42",
    product_name: "Storage",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-v2.devilop.me/home/storage-03/storage-03_1.jpg',
    product_thumbnail_two: 'https://ecoka-v2.devilop.me/home/storage-03/storage-03_2.jpg',
    product_thumbnail_three: 'https://ecoka-v2.devilop.me/home/storage-03/storage-03_3.jpg',
    product_thumbnail_four: 'https://ecoka-v2.devilop.me/home/storage-03/storage-03_4.jpg',
    product_thumbnail_five: 'https://ecoka-v2.devilop.me/home/storage-03/storage-03_5.jpg',
    product_thumbnail_six: 'https://ecoka-v2.devilop.me/home/storage-03/storage-03_6.jpg',
    product_price: '0',
    category_id: 1
  },
  // ======================================
  {
    product_id: "ECOKAPRODUCT43",
    product_name: "Coster",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-v2.devilop.me/kitchen/coster/coster_1.jpg',
    product_thumbnail_two: 'https://ecoka-v2.devilop.me/kitchen/coster/coster_2.jpg',
    product_thumbnail_three: 'https://ecoka-v2.devilop.me/kitchen/coster/coster_3.jpg',
    product_thumbnail_four: 'https://ecoka-v2.devilop.me/kitchen/coster/coster_4.jpg',
    product_thumbnail_five: 'https://ecoka-v2.devilop.me/kitchen/coster/coster_5.jpg',
    product_thumbnail_six: 'https://ecoka-v2.devilop.me/kitchen/coster/coster_6.jpg',
    product_price: '0',
    category_id: 2
  },
  {
    product_id: "ECOKAPRODUCT44",
    product_name: "Holder",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-v2.devilop.me/kitchen/holder/holder.jpg',
    product_thumbnail_two: '',
    product_thumbnail_three: '',
    product_thumbnail_four: '',
    product_thumbnail_five: '',
    product_thumbnail_six: '',
    product_price: '0',
    category_id: 2
  },
  {
    product_id: "ECOKAPRODUCT45",
    product_name: "Napkin Ring",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-v2.devilop.me/kitchen/napkin-ring/napkin-ring_1.jpg',
    product_thumbnail_two: 'https://ecoka-v2.devilop.me/kitchen/napkin-ring/napkin-ring_2.jpg',
    product_thumbnail_three: 'https://ecoka-v2.devilop.me/kitchen/napkin-ring/napkin-ring_3.jpg',
    product_thumbnail_four: 'https://ecoka-v2.devilop.me/kitchen/napkin-ring/napkin-ring_4.jpg',
    product_thumbnail_five: 'https://ecoka-v2.devilop.me/kitchen/napkin-ring/napkin-ring_5.jpg',
    product_thumbnail_six: 'https://ecoka-v2.devilop.me/kitchen/napkin-ring/napkin-ring_6.jpg',
    product_price: '0',
    category_id: 2
  },
  {
    product_id: "ECOKAPRODUCT46",
    product_name: "Placemat",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-v2.devilop.me/kitchen/placemat-01/placemat-01_1.jpg',
    product_thumbnail_two: 'https://ecoka-v2.devilop.me/kitchen/placemat-01/placemat-01_2.jpg',
    product_thumbnail_three: 'https://ecoka-v2.devilop.me/kitchen/placemat-01/placemat-01_3jpg',
    product_thumbnail_four: 'https://ecoka-v2.devilop.me/kitchen/placemat-01/placemat-01_4.jpg',
    product_thumbnail_five: 'https://ecoka-v2.devilop.me/kitchen/placemat-01/placemat-01_5.jpg',
    product_thumbnail_six: 'https://ecoka-v2.devilop.me/kitchen/placemat-01/placemat-01_6.jpg',
    product_price: '0',
    category_id: 2
  },
  {
    product_id: "ECOKAPRODUCT47",
    product_name: "Placemat",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-v2.devilop.me/kitchen/placemat-02/placemat-02_1.jpg',
    product_thumbnail_two: 'https://ecoka-v2.devilop.me/kitchen/placemat-02/placemat-02_2.jpg',
    product_thumbnail_three: 'https://ecoka-v2.devilop.me/kitchen/placemat-02/placemat-02_3jpg',
    product_thumbnail_four: 'https://ecoka-v2.devilop.me/kitchen/placemat-02/placemat-02_4.jpg',
    product_thumbnail_five: 'https://ecoka-v2.devilop.me/kitchen/placemat-02/placemat-02_5.jpg',
    product_thumbnail_six: 'https://ecoka-v2.devilop.me/kitchen/placemat-02/placemat-02_6.jpg',
    product_price: '0',
    category_id: 2
  },
  {
    product_id: "ECOKAPRODUCT48",
    product_name: "Placemat",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-v2.devilop.me/kitchen/placemat-03/placemat-03_1.jpg',
    product_thumbnail_two: 'https://ecoka-v2.devilop.me/kitchen/placemat-03/placemat-03_2.jpg',
    product_thumbnail_three: 'https://ecoka-v2.devilop.me/kitchen/placemat-03/placemat-03_3jpg',
    product_thumbnail_four: 'https://ecoka-v2.devilop.me/kitchen/placemat-03/placemat-03_4.jpg',
    product_thumbnail_five: 'https://ecoka-v2.devilop.me/kitchen/placemat-03/placemat-03_5.jpg',
    product_thumbnail_six: '',
    product_price: '0',
    category_id: 2
  },
  // ======================================
  {
    product_id: "ECOKAPRODUCT49",
    product_name: "Benches",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-v2.devilop.me/furniture/benches/benches.jpg',
    product_thumbnail_two: '',
    product_thumbnail_three: '',
    product_thumbnail_four: '',
    product_thumbnail_five: '',
    product_thumbnail_six: '',
    product_price: '0',
    category_id: 3
  },
  {
    product_id: "ECOKAPRODUCT50",
    product_name: "Bộ Sofa",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-v2.devilop.me/furniture/bo-sofa/bo-sofa.jpg',
    product_thumbnail_two: '',
    product_thumbnail_three: '',
    product_thumbnail_four: '',
    product_thumbnail_five: '',
    product_thumbnail_six: '',
    product_price: '0',
    category_id: 3
  },
  {
    product_id: "ECOKAPRODUCT51",
    product_name: "Chair",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-v2.devilop.me/furniture/chair/chair.jpg',
    product_thumbnail_two: '',
    product_thumbnail_three: '',
    product_thumbnail_four: '',
    product_thumbnail_five: '',
    product_thumbnail_six: '',
    product_price: '0',
    category_id: 3
  },
  {
    product_id: "ECOKAPRODUCT52",
    product_name: "Coffee Table",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-v2.devilop.me/furniture/coffee-table/coffee-table.jpg',
    product_thumbnail_two: '',
    product_thumbnail_three: '',
    product_thumbnail_four: '',
    product_thumbnail_five: '',
    product_thumbnail_six: '',
    product_price: '0',
    category_id: 3
  },
  {
    product_id: "ECOKAPRODUCT53",
    product_name: "Đôn",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-v2.devilop.me/furniture/don/don_1.jpg',
    product_thumbnail_two: 'https://ecoka-v2.devilop.me/furniture/don/don_2.jpg',
    product_thumbnail_three: '',
    product_thumbnail_four: '',
    product_thumbnail_five: '',
    product_thumbnail_six: '',
    product_price: '0',
    category_id: 3
  },
  {
    product_id: "ECOKAPRODUCT54",
    product_name: "Home Storage",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-v2.devilop.me/furniture/home-storage/home-storage_1.jpg',
    product_thumbnail_two: 'https://ecoka-v2.devilop.me/furniture/home-storage/home-storage_2.jpg',
    product_thumbnail_three: 'https://ecoka-v2.devilop.me/furniture/home-storage/home-storage_3.jpg',
    product_thumbnail_four: '',
    product_thumbnail_five: '',
    product_thumbnail_six: '',
    product_price: '0',
    category_id: 3
  },
  {
    product_id: "ECOKAPRODUCT55",
    product_name: "Sofa",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-v2.devilop.me/furniture/sofa/sofa.jpg',
    product_thumbnail_two: '',
    product_thumbnail_three: '',
    product_thumbnail_four: '',
    product_thumbnail_five: '',
    product_thumbnail_six: '',
    product_price: '0',
    category_id: 3
  },
  {
    product_id: "ECOKAPRODUCT56",
    product_name: "Sofa Table",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-v2.devilop.me/furniture/sofa-table/sofa-table_1.jpg',
    product_thumbnail_two: 'https://ecoka-v2.devilop.me/furniture/sofa-table/sofa-table_2.jpg',
    product_thumbnail_three: 'https://ecoka-v2.devilop.me/furniture/sofa-table/sofa-table_3.jpg',
    product_thumbnail_four: 'https://ecoka-v2.devilop.me/furniture/sofa-table/sofa-table_4.jpg',
    product_thumbnail_five: 'https://ecoka-v2.devilop.me/furniture/sofa-table/sofa-table_5.jpg',
    product_thumbnail_six: 'https://ecoka-v2.devilop.me/furniture/sofa-table/sofa-table_6.jpg',
    product_price: '0',
    category_id: 3
  },
  {
    product_id: "ECOKAPRODUCT57",
    product_name: "Sofa Table Restangle",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-v2.devilop.me/furniture/sofa-table-restangle/sofa-table-restangle.jpg',
    product_thumbnail_two: '',
    product_thumbnail_three: '',
    product_thumbnail_four: '',
    product_thumbnail_five: '',
    product_thumbnail_six: '',
    product_price: '0',
    category_id: 3
  },
  {
    product_id: "ECOKAPRODUCT58",
    product_name: "Tủ Kệ",
    product_description: "Mô Tả Sản Phẩm",
    product_thumbnail_one: 'https://ecoka-v2.devilop.me/furniture/tu-ke/tu-ke_1.jpg',
    product_thumbnail_two: 'https://ecoka-v2.devilop.me/furniture/tu-ke/tu-ke_2.jpg',
    product_thumbnail_three: 'https://ecoka-v2.devilop.me/furniture/tu-ke/tu-ke_3.jpg',
    product_thumbnail_four: 'https://ecoka-v2.devilop.me/furniture/tu-ke/tu-ke_4.jpg',
    product_thumbnail_five: '',
    product_thumbnail_six: '',
    product_price: '0',
    category_id: 3
  },
];
