export const URL = {
  ECOKA_LOGO_SQUARE: "https://ecoka.devilop.me/dev_ecoka_logo_text.png",
  ECOKA_LOGO_CIRCLE: "https://ecoka.devilop.me/dev_ecoka_logo_single.png",
  PRIMARY_BANNER: "https://ecoka.devilop.me/dev_banner.png",
  SECONDARY_BANNER: "https://ecoka.devilop.me/dev_sub_banner.png",
  TERTIARY_BANNER: "https://ecoka.devilop.me/dev_subscribe_banner.png",
  VIDEO: "https://rr4---sn-npoldn7l.googlevideo.com/videoplayback?expire=1709555377&ei=UWrlZY3xFsO-6dsP5fqqgAg&ip=172.233.39.215&id=o-ADiEcuPzk_9OR8PnDhI7L8f-lwyUH2_PtF3ikofQfQq5&itag=22&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&spc=UWF9fxWbCi7VtOHbTjtSQsy16ilHtyeWaXOswqPV3Dr6KbU&vprv=1&svpuc=1&mime=video%2Fmp4&cnr=14&ratebypass=yes&dur=30.093&lmt=1709533511475437&fexp=24007246&c=ANDROID&txp=6218224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AJfQdSswRQIhAMw5PiEjYWIJoKoCnTu14ncs8HbLBSSmehVw2drBpkgQAiASSGptIN-0-QSudrRaYteAnAeLRpDPOpd_KUgT5ivxDg%3D%3D&title=Ecoka+Video&redirect_counter=1&cm2rm=sn-5hnes676&req_id=6d0da5532a28a3ee&cms_redirect=yes&cmsv=e&mh=q_&mip=171.247.206.4&mm=34&mn=sn-npoldn7l&ms=ltu&mt=1709533493&mv=m&mvi=4&pl=21&lsparams=mh,mip,mm,mn,ms,mv,mvi,pl&lsig=APTiJQcwRgIhAN_mdSYWXL9qGl9yVbKzveoKHoaMF7_c331UPhibBdquAiEA4hZc59r47LxHZUzueTohTaASug9dF6IM5pFd-4NtiKA%3D",
  PRODUCT_THUMBNAL: "https://ecoka.devilop.me/dev_product.jpg",
  BLOG_THUMBNAL: "https://ecoka.devilop.me/dev_blog.jpg",
  VN_FLAG: "https://ecoka.devilop.me/dev_vn_flag.png",
  EN_FLAG: "https://ecoka.devilop.me/dev_en_flag.png",
  JA_FLAG: "https://ecoka.devilop.me/dev_jp_flag.png",
  FB_ICON: "https://ecoka.devilop.me/dev_facebook_icon.png",
  GG_ICON: "https://ecoka.devilop.me/dev_google_icon.png",
};
